### ISSUE TITLE
Unable to get setup

### ISSUE THREAD

**Issue by JNoVernay** [twrecked/hass-aarlo#1011]
Hi, 
Since a couple of version (currently 0.8.1.9), I had lost the flux of my arlo setup (it has been working for years). I've tried many things, create a new specific account as requested in the Arlo integration "read me", test it without trouble in Arlo's application, but no way to get it right in HA. HA is up to date. I've extracted what's about Arlo in the logfile attached.
Best regards,

[2024 Arlo.docx](https://github.com/user-attachments/files/17688647/2024.Arlo.docx)

**Comment by AnthonyRuelle** [comment]
Hi, 
Same problem here, it's broken with the new version (0.8.1.9)

**Comment by VistianOpenSource** [comment]
I had a similar issue, rolled back to the prior version in HACS and all works again.

**Comment by twrecked** [comment]
@JNoVernay It's looking like an IMAP error. Can you turn on [debug level reporting[(https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#enabling-debug) and try again?

@AnthonyRuelle @VistianOpenSource I don't think you're seeing the same issue but it's hard to tell from your reports. If you can provide some information about your set up and some of the logs you are seeing I'll take a look.

**Comment by JNoVernay** [comment]
Here it is...
[Arlo 2 2024.docx](https://github.com/user-attachments/files/17691968/Arlo.2.2024.docx)
Checked and replace email's address and passwords

**Comment by twrecked** [comment]
Can you upload it as plain text. Thanks.

**Comment by JNoVernay** [comment]
Is there a way to exchange on a more private canal? My capabilities to handle what is really important in are limited...

**Comment by twrecked** [comment]
you can email me at: steve.herrell@gmail.com

**Comment by VistianOpenSource** [comment]
Here is an extract from the log when I was running 0.8.1.9 . Once I rolled back to the prior version everything sprung back into life again. 

```
2024-11-10 10:29:00.551 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:02.277 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:02.545 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:04.126 INFO (SyncWorker_42) [pyaarlo] pyarlo 0.8.0.12 starting...
2024-11-10 10:29:04.341 INFO (SyncWorker_42) [pyaarlo] pyaarlo starting
2024-11-10 10:29:04.463 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:04.751 INFO (SyncWorker_42) [pyaarlo] skipping Charlie: state is removed
2024-11-10 10:29:04.872 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:04.886 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Aarlo for XXX EMAIL XXX for aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aarlo/__init__.py", line 276, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, ARLO_PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2147, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 5 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/aarlo/alarm_control_panel.py", line 24, in <module>
    from homeassistant.components.alarm_control_panel.const import (
ImportError: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel.const' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/const.py)
2024-11-10 10:29:05.904 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:07.979 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:08.151 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:10.140 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:10.493 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:11.430 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:13.317 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:13.481 DEBUG (MainThread) [custom_components.aarlo] async setup for aarlo
2024-11-10 10:29:13.481 DEBUG (MainThread) [custom_components.aarlo.cfg] _async_load_yaml1 file_name for /config/aarlo.yaml
2024-11-10 10:29:13.486 DEBUG (MainThread) [custom_components.aarlo.cfg] _async_load_yaml2 file_name for /config/aarlo.yaml
2024-11-10 10:29:13.491 DEBUG (MainThread) [custom_components.aarlo.cfg] _async_load_yaml3 file_name for /config/aarlo.yaml
2024-11-10 10:29:13.503 DEBUG (MainThread) [custom_components.aarlo.cfg] l-config-file=/config/aarlo.yaml
2024-11-10 10:29:13.504 DEBUG (MainThread) [custom_components.aarlo.cfg] l-main-config={'user_agent': 'arlo', 'backend': 'sse', 'media_retry': [5, 15, 25], 'mode_api': 'auto', 'mqtt_host': 'mqtt-cluster.arloxcld.com', 'injection_service': False, 'cache_videos': False, 'stream_snapshot': False, 'scan_interval': datetime.timedelta(seconds=60), 'reconnect_every': 0, 'db_ding_time': datetime.timedelta(seconds=10), 'tfa_total_timeout': datetime.timedelta(seconds=60), 'library_days': 27, 'packet_dump': False, 'cipher_list': '', 'http_max_size': 10, 'no_unicode_squash': True, 'mqtt_transport': 'tcp', 'serial_ids': False, 'stream_snapshot_stop': 0, 'verbose_debug': False, 'mqtt_hostname_check': True, 'refresh_devices_every': 2, 'save_updates_to': '', 'save_session': True, 'auth_host': 'https://ocapi-app.arlo.com', 'refresh_modes_every': 0, 'db_motion_time': datetime.timedelta(seconds=30), 'request_timeout': datetime.timedelta(seconds=15), 'snapshot_timeout': datetime.timedelta(seconds=45), 'recent_time': datetime.timedelta(seconds=3600), 'tfa_timeout': datetime.timedelta(seconds=3), 'host': 'https://myapi.arlo.com', 'last_format': '%m-%d %H:%M', 'no_media_upload': False, 'snapshot_checks': [], 'user_stream_delay': 1, 'stream_timeout': datetime.timedelta(seconds=120), 'hide_deprecated_services': True, 'save_media_to': '', 'http_connections': 5, 'conf_dir': ''}
2024-11-10 10:29:13.505 DEBUG (MainThread) [custom_components.aarlo.cfg] m-main-config={'username': 'XXX EMAIL XXX', 'password': 'XXX PASSWORD XXX', 'tfa_type': 'email', 'add_aarlo_prefix': True, 'tfa_source': 'imap', 'tfa_host': 'imap.gmail.com', 'tfa_username': 'XXX EMAIL XXX', 'tfa_password': 'XXX APP PASSWORD XXX', 'user_agent': 'arlo', 'backend': 'sse', 'media_retry': [5, 15, 25], 'mode_api': 'auto', 'mqtt_host': 'mqtt-cluster.arloxcld.com', 'injection_service': False, 'cache_videos': False, 'stream_snapshot': False, 'scan_interval': datetime.timedelta(seconds=60), 'reconnect_every': 0, 'db_ding_time': datetime.timedelta(seconds=10), 'tfa_total_timeout': datetime.timedelta(seconds=60), 'library_days': 27, 'packet_dump': False, 'cipher_list': '', 'http_max_size': 10, 'no_unicode_squash': True, 'mqtt_transport': 'tcp', 'serial_ids': False, 'stream_snapshot_stop': 0, 'verbose_debug': False, 'mqtt_hostname_check': True, 'refresh_devices_every': 2, 'save_updates_to': '', 'save_session': True, 'auth_host': 'https://ocapi-app.arlo.com', 'refresh_modes_every': 0, 'db_motion_time': datetime.timedelta(seconds=30), 'request_timeout': datetime.timedelta(seconds=15), 'snapshot_timeout': datetime.timedelta(seconds=45), 'recent_time': datetime.timedelta(seconds=3600), 'tfa_timeout': datetime.timedelta(seconds=3), 'host': 'https://myapi.arlo.com', 'last_format': '%m-%d %H:%M', 'no_media_upload': False, 'snapshot_checks': [], 'user_stream_delay': 1, 'stream_timeout': datetime.timedelta(seconds=120), 'hide_deprecated_services': True, 'save_media_to': '', 'http_connections': 5, 'conf_dir': ''}
2024-11-10 10:29:13.506 DEBUG (MainThread) [custom_components.aarlo.cfg] m-alarm-config={'disarmed_mode_name': 'disarmed', 'home_mode_name': 'home', 'away_mode_name': 'armed', 'night_mode_name': 'night', 'code_arm_required': False, 'code_disarm_required': False, 'trigger_time': datetime.timedelta(seconds=60), 'alarm_volume': 3, 'command_template': '{{action}}'}
2024-11-10 10:29:13.508 DEBUG (MainThread) [custom_components.aarlo.cfg] m-binary-sensor-config={'monitored_conditions': ['sound', 'motion', 'ding', 'cry', 'connectivity', 'contact', 'light', 'tamper', 'leak']}
2024-11-10 10:29:13.509 DEBUG (MainThread) [custom_components.aarlo.cfg] m-sensor-config={'monitored_conditions': ['last_capture', 'total_cameras', 'recent_activity', 'captured_today', 'battery_level', 'signal_strength', 'temperature', 'humidity', 'air_quality']}
2024-11-10 10:29:13.509 DEBUG (MainThread) [custom_components.aarlo.cfg] m-switch-config={'siren': True, 'all_sirens': True, 'siren_allow_off': True, 'siren_volume': 3, 'siren_duration': datetime.timedelta(seconds=10), 'snapshot': True, 'snapshot_timeout': datetime.timedelta(seconds=15), 'doorbell_silence': True}
2024-11-10 10:29:13.512 DEBUG (SyncWorker_20) [custom_components.aarlo.cfg] config={'username': 'XXX EMAIL XXX', 'password': 'XXX PASSWORD XXX', 'tfa_type': 'email', 'add_aarlo_prefix': True, 'tfa_source': 'imap', 'tfa_host': 'imap.gmail.com', 'tfa_username': 'XXX EMAIL XXX', 'tfa_password': 'XXX APP PASSWORD XXX', 'user_agent': 'arlo', 'backend': 'sse', 'media_retry': [5, 15, 25], 'mode_api': 'auto', 'mqtt_host': 'mqtt-cluster.arloxcld.com', 'injection_service': False, 'cache_videos': False, 'stream_snapshot': False, 'scan_interval': datetime.timedelta(seconds=60), 'reconnect_every': 0, 'db_ding_time': datetime.timedelta(seconds=10), 'tfa_total_timeout': datetime.timedelta(seconds=60), 'library_days': 27, 'packet_dump': False, 'cipher_list': '', 'http_max_size': 10, 'no_unicode_squash': True, 'mqtt_transport': 'tcp', 'serial_ids': False, 'stream_snapshot_stop': 0, 'verbose_debug': False, 'mqtt_hostname_check': True, 'refresh_devices_every': 2, 'save_updates_to': '', 'save_session': True, 'auth_host': 'https://ocapi-app.arlo.com', 'refresh_modes_every': 0, 'db_motion_time': datetime.timedelta(seconds=30), 'request_timeout': datetime.timedelta(seconds=15), 'snapshot_timeout': datetime.timedelta(seconds=45), 'recent_time': datetime.timedelta(seconds=3600), 'tfa_timeout': datetime.timedelta(seconds=3), 'host': 'https://myapi.arlo.com', 'last_format': '%m-%d %H:%M', 'no_media_upload': False, 'snapshot_checks': [], 'user_stream_delay': 1, 'stream_timeout': datetime.timedelta(seconds=120), 'hide_deprecated_services': True, 'save_media_to': '', 'http_connections': 5, 'conf_dir': ''}
2024-11-10 10:29:13.513 DEBUG (SyncWorker_20) [custom_components.aarlo.cfg] options={'username': 'XXX EMAIL XXX', 'password': 'XXX PASSWORD XXX', 'tfa_type': 'email', 'add_aarlo_prefix': True, 'tfa_source': 'imap', 'tfa_host': 'imap.gmail.com', 'tfa_username': 'XXX EMAIL XXX', 'tfa_password': 'XXX APP PASSWORD XXX', 'user_agent': 'arlo', 'backend': 'sse', 'media_retry': [5, 15, 25], 'mode_api': 'auto', 'mqtt_host': 'mqtt-cluster.arloxcld.com', 'injection_service': False, 'cache_videos': False, 'stream_snapshot': False, 'scan_interval': 60, 'reconnect_every': 0, 'db_ding_time': 10, 'tfa_total_timeout': 60, 'library_days': 27, 'packet_dump': False, 'cipher_list': '', 'http_max_size': 10, 'no_unicode_squash': True, 'mqtt_transport': 'tcp', 'serial_ids': False, 'stream_snapshot_stop': 0, 'verbose_debug': False, 'mqtt_hostname_check': True, 'refresh_devices_every': 2, 'save_updates_to': '', 'save_session': True, 'auth_host': 'https://ocapi-app.arlo.com', 'refresh_modes_every': 0, 'db_motion_time': 30, 'request_timeout': 15, 'snapshot_timeout': 45, 'recent_time': 3600, 'tfa_timeout': 3, 'host': 'https://myapi.arlo.com', 'last_format': '%m-%d %H:%M', 'no_media_upload': False, 'snapshot_checks': [], 'user_stream_delay': 1, 'stream_timeout': 120, 'hide_deprecated_services': True, 'save_media_to': '', 'http_connections': 5, 'conf_dir': '', 'dump': False, 'storage_dir': '/config/.aarlo', 'wait_for_initial_setup': False}
2024-11-10 10:29:13.513 INFO (SyncWorker_20) [pyaarlo] pyarlo 0.8.0.12 starting...
2024-11-10 10:29:13.521 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:13.745 INFO (SyncWorker_20) [pyaarlo] pyaarlo starting
2024-11-10 10:29:14.167 INFO (SyncWorker_20) [pyaarlo] skipping Charlie: state is removed
2024-11-10 10:29:14.313 DEBUG (SyncWorker_20) [custom_components.aarlo] login succeeded, attempt=1
2024-11-10 10:29:14.317 DEBUG (MainThread) [custom_components.aarlo] update hass data {'aarlo': {'username': 'XXX EMAIL XXX', 'password': 'XXX PASSWORD XXX', 'tfa_type': 'email', 'add_aarlo_prefix': True, 'tfa_source': 'imap', 'tfa_host': 'imap.gmail.com', 'tfa_username': 'XXX EMAIL XXX', 'tfa_password': 'XXX APP PASSWORD XXX', 'user_agent': 'arlo', 'backend': 'sse', 'media_retry': [5, 15, 25], 'mode_api': 'auto', 'mqtt_host': 'mqtt-cluster.arloxcld.com', 'injection_service': False, 'cache_videos': False, 'stream_snapshot': False, 'scan_interval': datetime.timedelta(seconds=60), 'reconnect_every': 0, 'db_ding_time': datetime.timedelta(seconds=10), 'tfa_total_timeout': datetime.timedelta(seconds=60), 'library_days': 27, 'packet_dump': False, 'cipher_list': '', 'http_max_size': 10, 'no_unicode_squash': True, 'mqtt_transport': 'tcp', 'serial_ids': False, 'stream_snapshot_stop': 0, 'verbose_debug': False, 'mqtt_hostname_check': True, 'refresh_devices_every': 2, 'save_updates_to': '', 'save_session': True, 'auth_host': 'https://ocapi-app.arlo.com', 'refresh_modes_every': 0, 'db_motion_time': datetime.timedelta(seconds=30), 'request_timeout': datetime.timedelta(seconds=15), 'snapshot_timeout': datetime.timedelta(seconds=45), 'recent_time': datetime.timedelta(seconds=3600), 'tfa_timeout': datetime.timedelta(seconds=3), 'host': 'https://myapi.arlo.com', 'last_format': '%m-%d %H:%M', 'no_media_upload': False, 'snapshot_checks': [], 'user_stream_delay': 1, 'stream_timeout': datetime.timedelta(seconds=120), 'hide_deprecated_services': True, 'save_media_to': '', 'http_connections': 5, 'conf_dir': ''}, 'alarm_control_panel': {'disarmed_mode_name': 'disarmed', 'home_mode_name': 'home', 'away_mode_name': 'armed', 'night_mode_name': 'night', 'code_arm_required': False, 'code_disarm_required': False, 'trigger_time': datetime.timedelta(seconds=60), 'alarm_volume': 3, 'command_template': '{{action}}'}, 'binary_sensor': {'monitored_conditions': ['sound', 'motion', 'ding', 'cry', 'connectivity', 'contact', 'light', 'tamper', 'leak']}, 'sensor': {'monitored_conditions': ['last_capture', 'total_cameras', 'recent_activity', 'captured_today', 'battery_level', 'signal_strength', 'temperature', 'humidity', 'air_quality']}, 'switch': {'siren': True, 'all_sirens': True, 'siren_allow_off': True, 'siren_volume': 3, 'siren_duration': datetime.timedelta(seconds=10), 'snapshot': True, 'snapshot_timeout': datetime.timedelta(seconds=15), 'doorbell_silence': True}}
2024-11-10 10:29:14.317 DEBUG (MainThread) [custom_components.aarlo] would try to add Shed
2024-11-10 10:29:14.317 DEBUG (MainThread) [custom_components.aarlo] would try to add Oak Tree
2024-11-10 10:29:14.318 DEBUG (MainThread) [custom_components.aarlo] would try to add Lounge-Office
2024-11-10 10:29:14.318 DEBUG (MainThread) [custom_components.aarlo] would try to add Lounge-Sitting Room
2024-11-10 10:29:14.318 DEBUG (MainThread) [custom_components.aarlo] would try to add Drive
2024-11-10 10:29:14.318 DEBUG (MainThread) [custom_components.aarlo] would try to add Sitting Room
2024-11-10 10:29:14.318 DEBUG (MainThread) [custom_components.aarlo] would try to add Balcony
2024-11-10 10:29:14.319 DEBUG (MainThread) [custom_components.aarlo] would try to add Front Door
2024-11-10 10:29:14.319 DEBUG (MainThread) [custom_components.aarlo] would try to add Charlie
2024-11-10 10:29:14.319 DEBUG (MainThread) [custom_components.aarlo] would try to add Birdbox
2024-11-10 10:29:14.319 DEBUG (MainThread) [custom_components.aarlo] would try to add Recycling
2024-11-10 10:29:14.319 DEBUG (MainThread) [custom_components.aarlo] would try to add Main Bedroom
2024-11-10 10:29:14.320 DEBUG (MainThread) [custom_components.aarlo] would try to add Garage
2024-11-10 10:29:14.332 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:14.360 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Aarlo for XXX EMAIL XXX for aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aarlo/__init__.py", line 276, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, ARLO_PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2147, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 5 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/aarlo/alarm_control_panel.py", line 24, in <module>
    from homeassistant.components.alarm_control_panel.const import (
ImportError: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel.const' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/const.py)
2024-11-10 10:29:15.533 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:15.968 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?
2024-11-10 10:29:16.979 WARNING (ArloEventStream) [pyaarlo] logged out? did you log in from elsewhere?

```

**Comment by twrecked** [comment]
@AnthonyRuelle 
@VistianOpenSource Seems like I jumped the gun with a deprecated warning fix. You'll need to stay on the older version until you upgrade home assistant.

**Comment by VistianOpenSource** [comment]
> @AnthonyRuelle @VistianOpenSource Seems like I jumped the gun with a deprecated warning fix. You'll need to stay on the older version until you upgrade home assistant.

So is the latest release dependant upon the absolutely latest current version of HA? I normally leave it until the end of the month before I do a HA update - hoping that any issues identified in that months release will have been ironed out before I upgrade.

**Comment by twrecked** [comment]
I guess it is. I got some bug reports in about deprecated warnings and fixed them with a "real" issue about the alarms. Serves me right for not procrastinating like I usually do.

**Comment by twrecked** [comment]
I'll close this one. And I'll wait longer next time before removing deprecated warnings!
