### ISSUE TITLE
_attr_frontend_stream_type causing errors

### ISSUE THREAD

**Issue by mikesalz** [twrecked/hass-aarlo#1023]
Getting this error which suggests it won't be an issue until June.  But still failing now.  Logs are flooded.  I think it started when I upgraded to HA 2024.12.1.

> Detected code that is setting the '_attr_frontend_stream_type' attribute in the ArloCam class, which is deprecated and will be removed in Home Assistant 2025.6

Full error below:

> 
> Logger: homeassistant
> Source: helpers/frame.py:227
> First occurred: 6:33:34 AM (422 occurrences)
> Last logged: 7:17:53 AM
> 
> Error doing job: Exception in callback Entity._async_write_ha_state_from_call_soon_threadsafe() (None)
> Error doing job: Exception in callback _TrackTimeInterval._interval_listener() (None)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 208, in report_usage
>     integration_frame = get_integration_frame(
>         exclude_integrations=exclude_integrations
>     )
>   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 113, in get_integration_frame
>     raise MissingIntegrationFrame
> homeassistant.helpers.frame.MissingIntegrationFrame
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
>     self._context.run(self._callback, *self._args)
>     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1014, in _async_write_ha_state_from_call_soon_threadsafe
>     self._async_write_ha_state()
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
>     self.__async_calculate_state()
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1087, in __async_calculate_state
>     if state_attributes := self.state_attributes:
>                            ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 812, in state_attributes
>     if frontend_stream_type := self.frontend_stream_type:
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 586, in frontend_stream_type
>     report_usage(
>     ~~~~~~~~~~~~^
>         (
>         ^
>     ...<4 lines>...
>         exclude_integrations={DOMAIN},
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     )
>     ^
>   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 227, in report_usage
>     raise RuntimeError(msg) from err
> RuntimeError: Detected code that is setting the '_attr_frontend_stream_type' attribute in the ArloCam class, which is deprecated and will be removed in Home Assistant 2025.6, . Please report this issue

**Comment by ibaeic** [comment]
See issue #1019

**Comment by mikesalz** [comment]
> See issue #1019

Thank you @ibaeic !  That resolved the issue for me.  I literally had thousands of errors in my log!
