### ISSUE TITLE
camera.enable_motion_detection throws 'list index out of range'

### ISSUE THREAD

**Issue by rbluff** [twrecked/hass-aarlo#108]
I only installed hass.io a couple of days ago, so I'm a complete newbie. Apologies in advance if this is a stupid question. 

I have installed v0.0.7-test02 on HassOS 2.12 and modified configuration.yaml as described in the instructions. 

As I understand it, I am supposed to call the ` camera.enable_motion_detection` service on each camera to enable motion detection, but calling it results in this error:

```
list index out of range

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 128, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 334, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 356, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/camera.py", line 313, in enable_motion_detection
    self.set_base_station_mode(ARLO_MODE_ARMED)
  File "/config/custom_components/aarlo/camera.py", line 308, in set_base_station_mode
    self._camera.base_station.mode = mode
  File "/config/custom_components/aarlo/pyaarlo/device.py", line 174, in base_station
    return self._arlo.base_stations[0]
IndexError: list index out of range
```

My interpretation is that the error is being thrown because there is no base station registered. I can see the two cameras themselves listed as entities, along with the motion and sound binary sensors etc, but I can't see any base station or alarm control panel entities. 

Should there be an alarm control panel / base station entity listed?

Thanks

[configuration.zip](https://github.com/twrecked/hass-aarlo/files/3508355/configuration.zip)

**Comment by twrecked** [comment]
What type of cameras and what type of base station is this? Your config looks good but I might need to add a new camera/base station type.

Did you give read/write access to the guest user?

**Comment by twrecked** [comment]
I forgot to address the camera motion question. That feature doesn't work well with Arlo (yet!). How it works is it looks for the base station associated with a camera and sets the mode to disarmed to stop motion detection and armed to enable it. This will also disable and enable detection for all cameras on that base station.

The solution is for me to create a custom mode and move cameras in and out of it as you enable/disable motion detection, I just just haven't had time to do that.

**Comment by rbluff** [comment]
Thanks for following up. 

The base station is a VMB4000r3 and the cameras are Pro 2 (H3). 

The Arlo guest user does not have admin rights - is that what you mean?

**Comment by twrecked** [comment]
Yes, the guest user needs to have admin access rights. I think not having admin access will stop the base stations from appearing.

**Comment by rbluff** [comment]
Ok thanks, I will try that.

**Comment by rbluff** [comment]
Motion detection seems to be working well now. Thanks again.
