### ISSUE TITLE
100.B1 - Unable to prepare setup for platform aarlo.camera: Unable to set up component.

### ISSUE THREAD

**Issue by Swiftnesses** [twrecked/hass-aarlo#122]
Hi,

Using the latest beta release I get:

<img width="764" alt="Screenshot 2019-10-06 at 08 42 43" src="https://user-images.githubusercontent.com/1001877/66265871-49b3fb00-e815-11e9-82cf-5d5794349af6.png">

```
Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 131, in setup
    http_connections=http_connections, http_max_size=http_max_size)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 67, in __init__
    self._parse_devices()
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 114, in _parse_devices
    for device in self._devices:
TypeError: 'NoneType' object is not iterable
```

**Comment by twrecked** [comment]
Can you try adding this to your config. The new code uses the new Arlo host by default.

```
aarlo:
    host: https://arlo.netgear.com/
```

**Comment by twrecked** [comment]
Did that work?

**Comment by Swiftnesses** [comment]
Sure did, thanks!
