### ISSUE TITLE
v0.6.10 -- various errors

### ISSUE THREAD

**Issue by aneisch** [twrecked/hass-aarlo#165]
Installed via HACS 0.21.1
```
arch | x86_64
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.7.6
timezone | America/Chicago
version | 0.105.2
virtualenv | false
```

```
Setup failed for aarlo: No setup function defined.
```
```
Platform error: alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 739, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 275, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/aarlo/alarm_control_panel.py", line 34, in <module>
    from . import CONF_ATTRIBUTION, DATA_ARLO, DEFAULT_BRAND
ImportError: cannot import name 'CONF_ATTRIBUTION' from 'custom_components.aarlo' (/config/custom_components/aarlo/__init__.py)
```

```
Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 739, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 275, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/aarlo/sensor.py", line 21, in <module>
    from . import CONF_ATTRIBUTION, DATA_ARLO, DEFAULT_BRAND
ImportError: cannot import name 'CONF_ATTRIBUTION' from 'custom_components.aarlo' (/config/custom_components/aarlo/__init__.py)
```

Tried uninstalling, reinstalling, deleting docker container and rebuilding, etc.

**Comment by twrecked** [comment]
A couple of people are seeing this. It's working from so I'm trying a reinstall to reproduce it.

**Comment by aneisch** [comment]
Looks to be a HACS issue, can you confirm @twrecked?

If I install your component via HACS 21.1 (latest) here is the aarlo custom_component directory content:
```
[aneisch@nuc-nuc custom_components]$ ls -la aarlo/
total 188
drwxr-xr-x  2 root    root     4096 Feb 10 20:17 .
drwxrwxr-x 12 aneisch aneisch   186 Feb 10 20:17 ..
-rw-r--r--  1 root    root    13931 Feb 10 20:17 alarm_control_panel.py
-rw-r--r--  1 root    root    16306 Feb 10 20:17 backend.py
-rw-r--r--  1 root    root     4489 Feb 10 20:17 background.py
-rw-r--r--  1 root    root    10050 Feb 10 20:17 base.py
-rw-r--r--  1 root    root     3762 Feb 10 20:17 binary_sensor.py
-rw-r--r--  1 root    root    26273 Feb 10 20:17 camera.py
-rw-r--r--  1 root    root     2848 Feb 10 20:17 cfg.py
-rw-r--r--  1 root    root     5085 Feb 10 20:17 constant.py
-rw-r--r--  1 root    root     6957 Feb 10 20:17 device.py
-rw-r--r--  1 root    root     2230 Feb 10 20:17 doorbell.py
-rw-r--r--  1 root    root     9423 Feb 10 20:17 __init__.py
-rw-r--r--  1 root    root     1649 Feb 10 20:17 light.py
-rw-r--r--  1 root    root      223 Feb 10 20:17 manifest.json
-rw-r--r--  1 root    root     6998 Feb 10 20:17 media_player.py
-rw-r--r--  1 root    root     6453 Feb 10 20:17 media.py
-rw-r--r--  1 root    root     5795 Feb 10 20:17 sensor.py
-rw-r--r--  1 root    root      865 Feb 10 20:17 services.yaml
-rw-r--r--  1 root    root     5874 Feb 10 20:17 sseclient.py
-rw-r--r--  1 root    root     2103 Feb 10 20:17 storage.py
-rw-r--r--  1 root    root     9702 Feb 10 20:17 switch.py
-rw-r--r--  1 root    root     2145 Feb 10 20:17 util.py
```

If I install via the previous version of HACS (0.20.9) here is the aarlo custom_component directory content:
```
[aneisch@nuc-nuc custom_components]$ ls -la aarlo
total 100
drwxr-xr-x  3 root    root      226 Feb 10 20:21 .
drwxrwxr-x 13 aneisch aneisch   203 Feb 10 20:21 ..
-rw-r--r--  1 root    root    13931 Feb 10 20:21 alarm_control_panel.py
-rw-r--r--  1 root    root     3762 Feb 10 20:21 binary_sensor.py
-rw-r--r--  1 root    root    25065 Feb 10 20:21 camera.py
-rw-r--r--  1 root    root     5929 Feb 10 20:21 __init__.py
-rw-r--r--  1 root    root     7303 Feb 10 20:21 light.py
-rw-r--r--  1 root    root      223 Feb 10 20:21 manifest.json
-rw-r--r--  1 root    root     6998 Feb 10 20:21 media_player.py
drwxr-xr-x  2 root    root      250 Feb 10 20:21 pyaarlo
-rw-r--r--  1 root    root     5795 Feb 10 20:21 sensor.py
-rw-r--r--  1 root    root      865 Feb 10 20:21 services.yaml
-rw-r--r--  1 root    root     9702 Feb 10 20:21 switch.py
```

**Comment by twrecked** [comment]
I'm having a hell of time getting HACS working tonight, I'm seeing nothing but 403 Forbidden errors from github.

But I think your conclusion is correct.  Both directories have a `__init__.py` file and I think the `aarlo/pyaarlo` one is clobbering the `aarlo` one and wiping out the definitions we need.

**Comment by aneisch** [comment]
There's an issue opened with HACS mentioning directory issues with Appdaemon apps as well. I'm pretty satisfied that the issue lies there. Feel free to close this issue!

BTW.. thanks for the awesome integration!

**Comment by twrecked** [comment]
Once again, thanks for investigating!

**Comment by 5and0** [comment]
I have worked around with the following:
- Downgrade HACS to 0.20.9
- Reboot system
- reinstall hass-aarlo
- restart hass
