### ISSUE TITLE
Arlo Video Doorbell "Entity id already exists" Error on startup

### ISSUE THREAD

**Issue by baurandr** [twrecked/hass-aarlo#197]
After adding the Arlo Video Doorbell I have started getting 3 errors on startup:

```
2020-03-24 17:18:53 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: binary_sensor.aarlo_motion_front_door. Platform aarlo does not generate unique IDs

2020-03-24 17:18:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.aarlo_signal_strength_front_door. Platform aarlo does not generate unique IDs

2020-03-24 17:18:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.aarlo_battery_level_front_door. Platform aarlo does not generate unique IDs
```

I believe I tracked it down to the fact that the Arlo Video Doorbell shows up in arlo.cameras & arlo.doorbells.  Because of this it adds the motion, battery_level, and signal_strength twice in the async_setup_platform calls.  This generates a total of 3 errors.

I verified the 3 errors go away by modifying binary_sensor.py and sensor.py as shown below to explicitly check and not append these sensor types under the doorbell FOR loop, but I'm guessing this won't work for non-video doorbells.  I'm sure there is a more elegant solution to this but I am not knowledgeable enough to figure it out!
```
            for camera in arlo.cameras:
                if camera.has_capability(sensor_type):
                    name = '{0} {1}'.format(SENSOR_TYPES[sensor_type][0], camera.name)
                    sensors.append(ArloSensor(name, camera, sensor_type))
            for doorbell in arlo.doorbells:
                if doorbell.has_capability(sensor_type) and sensor_type != 'battery_level' and sensor_type != 'signal_strength':
                    name = '{0} {1}'.format(SENSOR_TYPES[sensor_type][0], doorbell.name)
                    sensors.append(ArloSensor(name, doorbell, sensor_type))
```
```
        for camera in arlo.cameras:
            if camera.has_capability(SENSOR_TYPES.get(sensor_type)[2]):
                sensors.append(ArloBinarySensor(camera, sensor_type))
        for doorbell in arlo.doorbells:
            #AWB added and to if statment below
            if doorbell.has_capability(SENSOR_TYPES.get(sensor_type)[2]) and sensor_type != 'motion':
                sensors.append(ArloBinarySensor(doorbell, sensor_type))
```

**Comment by twrecked** [comment]
I'm assuming you don't have a camera with the same name as the door bell?

Do you have a model number of the doorbell? The nicest solution is probably to remove the capability from the doorbell.

**Comment by baurandr** [comment]
Correct, I do not have any other cameras with the same name.  The model number is AVD1001Ar1.2

**Comment by twrecked** [comment]
I fixed it with #198 . Should be in https://github.com/twrecked/hass-aarlo/releases/tag/v0.6.18.2

Let me know how that works.

**Comment by baurandr** [comment]
Wow, that was quick!  You're awesome, it's fixed!

**Comment by twrecked** [comment]
Glad it worked!
