### ISSUE TITLE
Error in _init_.py

### ISSUE THREAD

**Issue by devinhedge** [twrecked/hass-aarlo#202]
Getting ERROR in custom_components/aarlo/pyaarlo/__init__.py:67

Log Details (ERROR)

Logger: homeassistant.setup
Source: custom_components/aarlo/pyaarlo/__init__.py:67
First occurred: 1:24:57 PM (1 occurrences)
Last logged: 1:24:57 PM
Error during setup of component aarlo 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 183, in setup
    hide_deprecated_services=hide_deprecated_services,verbose_debug=verbose_debug)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 67, in __init__
    for device in self._devices:
TypeError: 'NoneType' object is not iterable
```

**Comment by twrecked** [comment]
What version of hass-arlo are you using?

**Comment by devinhedge** [comment]
Installed from HACS installer. ./aalo/_init_.py has 0.6.17 in it.

**Comment by devinhedge** [comment]
Looks like there are some deltas between trunk and what HACS installed.

**Comment by twrecked** [comment]
You need 0.6.18.2. Arlo changed their authentication mechanisms.

**Comment by devinhedge** [comment]
Fascinating. Okay. I just downloaded the trunk and it's got a different issue. I'll try to pull 0.6.18.2.

**Comment by devinhedge** [comment]
Are the releases not tagged?

**Comment by devinhedge** [comment]
Okay that was weird. They are definitely tagged.

**Comment by twrecked** [comment]
Trunk is a bit experimental at the moment - it has 2FA and lots of code tidy... but if you kept the error that would be cool.

**Comment by devinhedge** [comment]
Okay. I tried 0.6.18.2 and 0.6.18.3. Still getting the following error:

```
2020-03-28 13:18:23 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 183, in setup
    hide_deprecated_services=hide_deprecated_services,verbose_debug=verbose_debug)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 67, in __init__
    for device in self._devices:
TypeError: 'NoneType' object is not iterable
```

**Comment by devinhedge** [comment]
When I look at the instantiation of the PyArlo class as arlo, I see on line 183, referred to by the error this:

```File "/config/custom_components/aarlo/__init__.py", line 183, in setup
    hide_deprecated_services=hide_deprecated_services,verbose_debug=verbose_debug)
```

When I go look at the constructor in the PyArlo library, I don't see an assignment for the two passed varibles of 
```hide_deprecated_services```
or
```verbose_debug```

Should there be a handler for them?

**Comment by twrecked** [comment]
They get passed to the ArloCfg class. I'm thinking it's still failing to login - I should be handling the `self._device` being `None` better.

Can you try the latest 0.6.89 build with `verbose_debug: True` in your config? It's going to print out a lot more information and let me know what's wrong.

Like I said, Arlo changed their auth mechanism and I might have missed some calls I need to make.

**Comment by devinhedge** [comment]
Logger: homeassistant.setup
Source: custom_components/aarlo/pyaarlo/tfa.py:25
First occurred: 6:30:26 PM (1 occurrences)
Last logged: 6:30:26 PM

 Error during setup of component aarlo 

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 198, in setup
    imap_host=imap_host, imap_username=imap_username, imap_password=imap_password)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 45, in __init__
    self._be = ArloBackEnd(self)
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 43, in __init__
    self._logged_in = self._login()
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 487, in _login
    if not self._auth():
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 413, in _auth
    if not tfa.start():
  File "/config/custom_components/aarlo/pyaarlo/tfa.py", line 25, in start
    self._imap = imaplib.IMAP4_SSL(self._arlo.cfg.imap_host)
  File "/usr/local/lib/python3.7/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 1301, in open
    IMAP4.open(self, host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 299, in open
    self.sock = self._create_socket()
  File "/usr/local/lib/python3.7/imaplib.py", line 1291, in _create_socket
    sock = IMAP4._create_socket(self)
  File "/usr/local/lib/python3.7/imaplib.py", line 289, in _create_socket
    return socket.create_connection((host, self.port))
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve```

**Comment by devinhedge** [comment]
FWIW: I don't have 2FA turned on or the mail settings configured.

**Comment by devinhedge** [comment]
okay... here we go... with version 0.6.89-beta.3

```
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.setup] Setting up aarlo
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.components.switch] Setting up switch.vesync
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.setup] Setup of domain light took 0.5 seconds.
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] Cfg started
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting
2020-03-28 18:47:14 WARNING (SyncWorker_8) [pyaarlo] file not read
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] custom connections 5:10
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.setup] Setting up coronavirus
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] login attempt #1
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting request=https://ocapi-app.arlo.com/api/auth
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting request={'email': 'this@isnotmyrealemail.com', 'password': 'thisisnotmyrealpassword', 'language': 'en', 'EnvSource': 'prod'}
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting request={'Auth-Version': '2', 'Accept': 'application/json, text/plain, */*', 'Referer': 'https://my.arlo.com', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)', 'Source': 'arloCamWeb'}
2020-03-28 18:47:15 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 3.9 seconds.
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] finish request=200
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] { 'data': { 'MFA_State': 'ENABLED',
            '_type': 'AccessTokenV2',
            'authCompleted': False,
            'authenticated': 1585435634,
            'expiresIn': 1586731634,
            'issued': 1585435634,
            'mfa': True,
            'token': '<redacted_token>',
            'type': 'USER',
            'userId': '114-50491'},
  'domain': 'ocapi-app.arlo.com',
  'meta': {'code': 200}}
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] need 2FA...
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] getting tfa choices
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] starting request=https://ocapi-app.arlo.com/api/getFactors?data = 1585435635
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] starting request={}
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] starting request={'Auth-Version': '2', 'Accept': 'application/json, text/plain, */*', 'Referer': 'https://my.arlo.com', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)', 'Source': 'arloCamWeb', 'Authorization': 'Ml9vUko0NHFCc3I1XzB0WjlOT01oeUlsbGxKV01OQzE4RGJuWE1YRnJMVFRXWEdJUWRUQk4wZmR1UzVUalJSYTFGNzd6enJGOFM1dGxfS0pIbUQxZ3FEeUtKOS11STlwSEtPZ0JsRFk1aEJJTFFNLTdwdG9jLTZuSVhweHhMVTQyWG5BaWpGVWhkUWpnZ0UtSENqV2JiaWpCeVhUeEE5cDZrbUNUcjZnTWJLY1k5bU1NTlNnRDZRMENOdFRNMURDYXp3eGFGdnBQTHJWa2R1bUdFR1Z3YlNNWnphVnhxaThqWDJXNjBlenNKMnJFSlp5RERhSnpRNzg4ZG1PNm85ZjZCdzlRZHI4c3ptQVE2VjNhNWpPU2ljN3p2bDVpNUhkX3VzTG5idm5pdG1lUGdPcGREN1E0X2loaHNucmlHVGRXRUdQeWlrYW5WbG1SUHg0dkRJMEtfSkMx'}
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] finish request=200
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] { 'data': { 'MFA_State': 'ENABLED',
            '_type': '_Collection',
            'items': [ { '_type': 'SecondFactor',
                         'applicationId': '54aa099e-366f-47b5-939a-bff713e1bd96',
                         'applicationName': 'Generic',
                         'displayName': '19193358497',
                         'factorId': 'UGluZ0lkU0RLOlNNUzowNzVjYjZlMy1lNmVhLWJhY2YtMDc1Yy1iNmUzZTZlYWJhY2Y6NTRhYTA5OWUtMzY2Zi00N2I1LTkzOWEtYmZmNzEzZTFiZDk2',
                         'factorNickname': '19193358497',
                         'factorRole': 'PRIMARY',
                         'factorType': 'SMS'},
                       { '_type': 'SecondFactor',
                         'applicationId': '54aa099e-366f-47b5-939a-bff713e1bd96',
                         'applicationName': 'Generic',
                         'displayName': 'devin@devinhedge.com',
                         'factorId': 'UGluZ0lkU0RLOkVNQUlMOjJmMjRiYzQ0LTgzNDYtYjZjZC0yZjI0LWJjNDQ4MzQ2YjZjZDo1NGFhMDk5ZS0zNjZmLTQ3YjUtOTM5YS1iZmY3MTNlMWJkOTY=',
                         'factorNickname': 'devin@devinhedge.com',
                         'factorRole': 'SECONDARY',
                         'factorType': 'EMAIL'}]},
  'meta': {'code': 200}}
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] looking for email
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] 2fa is using imap
2020-03-28 18:47:16 INFO (MainThread) [homeassistant.components.konnected.panel] pushing settings to device 807d3a7f721e
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 198, in setup
    imap_host=imap_host, imap_username=imap_username, imap_password=imap_password)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 45, in __init__
    self._be = ArloBackEnd(self)
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 43, in __init__
    self._logged_in = self._login()
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 487, in _login
    if not self._auth():
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 413, in _auth
    if not tfa.start():
  File "/config/custom_components/aarlo/pyaarlo/tfa.py", line 25, in start
    self._imap = imaplib.IMAP4_SSL(self._arlo.cfg.imap_host)
  File "/usr/local/lib/python3.7/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 1301, in open
    IMAP4.open(self, host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 299, in open
    self.sock = self._create_socket()
  File "/usr/local/lib/python3.7/imaplib.py", line 1291, in _create_socket
    sock = IMAP4._create_socket(self)
  File "/usr/local/lib/python3.7/imaplib.py", line 289, in _create_socket
    return socket.create_connection((host, self.port))
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.alarm_control_panel: Unable to set up component.
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.sensor: Unable to set up component.
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.media_player: Unable to set up component.
```

**Comment by devinhedge** [comment]
This is the redacted debug:
```
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.setup] Setting up aarlo
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.components.switch] Setting up switch.vesync
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.setup] Setup of domain light took 0.5 seconds.
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] Cfg started
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting
2020-03-28 18:47:14 WARNING (SyncWorker_8) [pyaarlo] file not read
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] custom connections 5:10
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.setup] Setting up coronavirus
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] login attempt #1
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting request=https://ocapi-app.arlo.com/api/auth
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting request={'email': 'this@isnotmyrealemail.com', 'password': 'thisisnotmyrealpassword', 'language': 'en', 'EnvSource': 'prod'}
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting request={'Auth-Version': '2', 'Accept': 'application/json, text/plain, */*', 'Referer': 'https://my.arlo.com', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)', 'Source': 'arloCamWeb'}
2020-03-28 18:47:15 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 3.9 seconds.
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] finish request=200
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] { 'data': { 'MFA_State': 'ENABLED',
            '_type': 'AccessTokenV2',
            'authCompleted': False,
            'authenticated': 1585435634,
            'expiresIn': 1586731634,
            'issued': 1585435634,
            'mfa': True,
            'token': '<redacted_token>',
            'type': 'USER',
            'userId': '114-50491'},
  'domain': 'ocapi-app.arlo.com',
  'meta': {'code': 200}}
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] need 2FA...
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] getting tfa choices
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] starting request=https://ocapi-app.arlo.com/api/getFactors?data = 1585435635
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] starting request={}
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] starting request={'Auth-Version': '2', 'Accept': 'application/json, text/plain, */*', 'Referer': 'https://my.arlo.com', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)', 'Source': 'arloCamWeb', 'Authorization': 'Ml9vUko0NHFCc3I1XzB0WjlOT01oeUlsbGxKV01OQzE4RGJuWE1YRnJMVFRXWEdJUWRUQk4wZmR1UzVUalJSYTFGNzd6enJGOFM1dGxfS0pIbUQxZ3FEeUtKOS11STlwSEtPZ0JsRFk1aEJJTFFNLTdwdG9jLTZuSVhweHhMVTQyWG5BaWpGVWhkUWpnZ0UtSENqV2JiaWpCeVhUeEE5cDZrbUNUcjZnTWJLY1k5bU1NTlNnRDZRMENOdFRNMURDYXp3eGFGdnBQTHJWa2R1bUdFR1Z3YlNNWnphVnhxaThqWDJXNjBlenNKMnJFSlp5RERhSnpRNzg4ZG1PNm85ZjZCdzlRZHI4c3ptQVE2VjNhNWpPU2ljN3p2bDVpNUhkX3VzTG5idm5pdG1lUGdPcGREN1E0X2loaHNucmlHVGRXRUdQeWlrYW5WbG1SUHg0dkRJMEtfSkMx'}
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] finish request=200
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] { 'data': { 'MFA_State': 'ENABLED',
            '_type': '_Collection',
            'items': [ { '_type': 'SecondFactor',
                         'applicationId': '54aa099e-366f-47b5-939a-bff713e1bd96',
                         'applicationName': 'Generic',
                         'displayName': '19193358497',
                         'factorId': 'UGluZ0lkU0RLOlNNUzowNzVjYjZlMy1lNmVhLWJhY2YtMDc1Yy1iNmUzZTZlYWJhY2Y6NTRhYTA5OWUtMzY2Zi00N2I1LTkzOWEtYmZmNzEzZTFiZDk2',
                         'factorNickname': '19193358497',
                         'factorRole': 'PRIMARY',
                         'factorType': 'SMS'},
                       { '_type': 'SecondFactor',
                         'applicationId': '54aa099e-366f-47b5-939a-bff713e1bd96',
                         'applicationName': 'Generic',
                         'displayName': 'this@isnotmyrealemail.com',
                         'factorId': 'UGluZ0lkU0RLOkVNQUlMOjJmMjRiYzQ0LTgzNDYtYjZjZC0yZjI0LWJjNDQ4MzQ2YjZjZDo1NGFhMDk5ZS0zNjZmLTQ3YjUtOTM5YS1iZmY3MTNlMWJkOTY=',
                         'factorNickname': 'this@isnotmyrealemail.com',
                         'factorRole': 'SECONDARY',
                         'factorType': 'EMAIL'}]},
  'meta': {'code': 200}}
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] looking for email
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] 2fa is using imap
2020-03-28 18:47:16 INFO (MainThread) [homeassistant.components.konnected.panel] pushing settings to device 807d3a7f721e
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 198, in setup
    imap_host=imap_host, imap_username=imap_username, imap_password=imap_password)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 45, in __init__
    self._be = ArloBackEnd(self)
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 43, in __init__
    self._logged_in = self._login()
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 487, in _login
    if not self._auth():
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 413, in _auth
    if not tfa.start():
  File "/config/custom_components/aarlo/pyaarlo/tfa.py", line 25, in start
    self._imap = imaplib.IMAP4_SSL(self._arlo.cfg.imap_host)
  File "/usr/local/lib/python3.7/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 1301, in open
    IMAP4.open(self, host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 299, in open
    self.sock = self._create_socket()
  File "/usr/local/lib/python3.7/imaplib.py", line 1291, in _create_socket
    sock = IMAP4._create_socket(self)
  File "/usr/local/lib/python3.7/imaplib.py", line 289, in _create_socket
    return socket.create_connection((host, self.port))
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.alarm_control_panel: Unable to set up component.
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.sensor: Unable to set up component.
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.media_player: Unable to set up component.
```

**Comment by devinhedge** [comment]
This is the redacted debug:
```
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.setup] Setting up aarlo
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.components.switch] Setting up switch.vesync
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.setup] Setup of domain light took 0.5 seconds.
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] Cfg started
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting
2020-03-28 18:47:14 WARNING (SyncWorker_8) [pyaarlo] file not read
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] custom connections 5:10
2020-03-28 18:47:14 INFO (MainThread) [homeassistant.setup] Setting up coronavirus
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] login attempt #1
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting request=https://ocapi-app.arlo.com/api/auth
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting request={'email': 'this@isnotmyrealemail.com', 'password': 'thisisnotmyrealpassword', 'language': 'en', 'EnvSource': 'prod'}
2020-03-28 18:47:14 DEBUG (SyncWorker_8) [pyaarlo] starting request={'Auth-Version': '2', 'Accept': 'application/json, text/plain, */*', 'Referer': 'https://my.arlo.com', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)', 'Source': 'arloCamWeb'}
2020-03-28 18:47:15 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 3.9 seconds.
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] finish request=200
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] { 'data': { 'MFA_State': 'ENABLED',
            '_type': 'AccessTokenV2',
            'authCompleted': False,
            'authenticated': 1585435634,
            'expiresIn': 1586731634,
            'issued': 1585435634,
            'mfa': True,
            'token': '<redacted_token>',
            'type': 'USER',
            'userId': '114-50491'},
  'domain': 'ocapi-app.arlo.com',
  'meta': {'code': 200}}
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] need 2FA...
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] getting tfa choices
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] starting request=https://ocapi-app.arlo.com/api/getFactors?data = 1585435635
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] starting request={}
2020-03-28 18:47:15 DEBUG (SyncWorker_8) [pyaarlo] starting request={'Auth-Version': '2', 'Accept': 'application/json, text/plain, */*', 'Referer': 'https://my.arlo.com', 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_2 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B202 NETGEAR/v1 (iOS Vuezone)', 'Source': 'arloCamWeb', 'Authorization': '<token>'}
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] finish request=200
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] { 'data': { 'MFA_State': 'ENABLED',
            '_type': '_Collection',
            'items': [ { '_type': 'SecondFactor',
                         'applicationId': '54aa099e-366f-47b5-939a-bff713e1bd96',
                         'applicationName': 'Generic',
                         'displayName': '19193358497',
                         'factorId': '<token>',
                         'factorNickname': '19193358497',
                         'factorRole': 'PRIMARY',
                         'factorType': 'SMS'},
                       { '_type': 'SecondFactor',
                         'applicationId': '54aa099e-366f-47b5-939a-bff713e1bd96',
                         'applicationName': 'Generic',
                         'displayName': 'this@isnotmyrealemail.com',
                         'factorId': '<token>',
                         'factorNickname': 'this@isnotmyrealemail.com',
                         'factorRole': 'SECONDARY',
                         'factorType': 'EMAIL'}]},
  'meta': {'code': 200}}
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] looking for email
2020-03-28 18:47:16 DEBUG (SyncWorker_8) [pyaarlo] 2fa is using imap
2020-03-28 18:47:16 INFO (MainThread) [homeassistant.components.konnected.panel] pushing settings to device 807d3a7f721e
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 198, in setup
    imap_host=imap_host, imap_username=imap_username, imap_password=imap_password)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 45, in __init__
    self._be = ArloBackEnd(self)
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 43, in __init__
    self._logged_in = self._login()
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 487, in _login
    if not self._auth():
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 413, in _auth
    if not tfa.start():
  File "/config/custom_components/aarlo/pyaarlo/tfa.py", line 25, in start
    self._imap = imaplib.IMAP4_SSL(self._arlo.cfg.imap_host)
  File "/usr/local/lib/python3.7/imaplib.py", line 1288, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 1301, in open
    IMAP4.open(self, host, port)
  File "/usr/local/lib/python3.7/imaplib.py", line 299, in open
    self.sock = self._create_socket()
  File "/usr/local/lib/python3.7/imaplib.py", line 1291, in _create_socket
    sock = IMAP4._create_socket(self)
  File "/usr/local/lib/python3.7/imaplib.py", line 289, in _create_socket
    return socket.create_connection((host, self.port))
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.alarm_control_panel: Unable to set up component.
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.sensor: Unable to set up component.
2020-03-28 18:47:16 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.media_player: Unable to set up component.
```

Geez... there are lots of callback tokens in there.

**Comment by twrecked** [comment]
Can you try using the same login on the website?

It's looking like 2FA has been turned on - the code looks for `authCompleted` in the return of the first  authentication packet. In this case you got `False` meaning it needs secondary auth.

**Comment by devinhedge** [comment]
Looks like we found a bug in Arlo's Account page. When you delete your 2FA information, it doesn't save it. I was able to delete it through the iOS app, but not the web page. Recreated it twice to make sure I wasn't missing something. This isn't a bug in your code and the Beta worked nicely.

**Comment by twrecked** [comment]
Arlo has a lot of quirks. I love the cameras but everybody's set up seems to work differently. Hence the plethora of options available to the module!

Glad you got it working and thanks for trying the beta.
