### ISSUE TITLE
login failed on pyaarlo

### ISSUE THREAD

**Issue by chris-chensy** [twrecked/hass-aarlo#265]
Hello, I encountered a login error since yesterday with the plugin. None of the components is currently available. I'm not sure if this is due to the change from Arlo Web Page or just my home network. I can log on the web portal using my mobile phone or hotspot to my pc. When I log on within my home wifi network using Chrome, it shows an error: 
'_Access to XMLHttpRequest at 'https://ocapi-app.arlo.com/api/auth' from origin 'https://my.arlo.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource._' 

Below is the hass debug info:

```
2020-05-25 13:41:18 DEBUG (SyncWorker_12) [pyaarlo] login failed
2020-05-25 13:41:18 WARNING (SyncWorker_12) [pyaarlo] failed to log in
2020-05-25 13:41:18 INFO (SyncWorker_12) [pyaarlo] pyaarlo starting

2020-05-25 13:41:19 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 175, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 184, in setup
    hide_deprecated_services=hide_deprecated_services,verbose_debug=verbose_debug)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 67, in __init__
    for device in self._devices:
TypeError: 'NoneType' object is not iterable
```

**Comment by chris-chensy** [comment]
Please ignore the error above. Very strangely, it works again when I try it today. Not sure if it was the issue with Arlo web portal or my home internet. I did not change anything locally though...
