### ISSUE TITLE
New Setup - Error during setup of component aarlo

### ISSUE THREAD

**Issue by ACA30** [twrecked/hass-aarlo#273]
I'm setting this up for the first time, and I'm having a few issues (hopefully it's not just me, haha)... I've added everything (aarlo, alarm_control_panel, camera, sensor, binary_sensor, and media_player) in configuration.yaml, but when I restart HASS, it does not work. I get the following notification:
```
Invalid config
The following integrations and platforms could not be set up:

aarlo
aarlo.media_player
aarlo.binary_sensor
aarlo.alarm_control_panel
aarlo.sensor
aarlo.camera
Please check your config.
```

This is the error I'm getting:
```
2020-07-05 15:00:42 WARNING (MainThread) [homeassistant.components.media_player] MediaPlayerDevice is deprecated, modify ArloMediaPlayerDevice to extend MediaPlayerEntity
2020-07-05 15:00:44 WARNING (SyncWorker_5) [pyaarlo] file not read
2020-07-05 15:00:46 WARNING (SyncWorker_5) [pyaarlo] failed to log in
2020-07-05 15:00:46 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 193, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 185, in setup
    hide_deprecated_services=hide_deprecated_services,verbose_debug=verbose_debug)
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 67, in __init__
    for device in self._devices:
TypeError: 'NoneType' object is not iterable
2020-07-05 15:00:46 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.media_player: Unable to set up component.
2020-07-05 15:00:46 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.binary_sensor: Unable to set up component.
2020-07-05 15:00:46 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.alarm_control_panel: Unable to set up component.
2020-07-05 15:00:46 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.sensor: Unable to set up component.
2020-07-05 15:00:46 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.camera: Unable to set up component.
```

I'm using HASS v0.112.2 & AArlo v0.6.19.1.

Thanks!

**Comment by ACA30** [comment]
...Of course, it was an issue with me being stupid. It was trying to do SMS verification, and turning that off fixed it.

**Comment by twrecked** [comment]
Glad you got it working! The new code handles no devices in a much nicer way.
