### ISSUE TITLE
Unable to start stream

### ISSUE THREAD

**Issue by ferdyh** [twrecked/hass-aarlo#295]
I have an Arlo Baby camera; Added aarlo to Home Assistant and trying to play it using TileBoard on Home Assistant. I added the camera as 'TYPES.CAMERA_STREAM'. When I click to open the stream I get the following error messages:

```
2020-08-05 14:48:31 INFO (MainThread) [homeassistant.components.stream] Started stream: https://arlostreaming416-z1-prod.wowza.arlo.com:80/stream/[camera-id]_1596631711371.mpd?egressToken=[guid]&userAgent=web&cameraId=[camera-id]_1596631711371&txnId=be![guid]
2020-08-05 14:48:31 DEBUG (ArloEventStream) [pyaarlo] sending cameras/[camera-id] to [camera-id]
2020-08-05 14:48:31 DEBUG (ArloEventStream) [pyaarlo] Babycam BASE got cameras/[camera-id]
2020-08-05 14:48:31 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/[camera-id]/activityState=userStreamActive
2020-08-05 14:48:31 DEBUG (ArloEventStream) [pyaarlo] Babycam CAMERA got one cameras/[camera-id]
2020-08-05 14:48:31 DEBUG (ArloEventStream) [pyaarlo] _event::stream::activities={'user-stream-active', 'user-stream'}
2020-08-05 14:48:31 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/[camera-id]/activityState=userStreamActive
2020-08-05 14:48:32 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-08-05 14:48:32 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-08-05!
2020-08-05 14:48:32 DEBUG (ArloBackgroundWorker) [pyaarlo] pinging Babycam
2020-08-05 14:48:32 DEBUG (ArloBackgroundWorker) [pyaarlo] notify+response running
2020-08-05 14:48:32 DEBUG (ArloBackgroundWorker) [pyaarlo] post+response running
2020-08-05 14:48:32 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/[camera-id]/connectionState=available
Exception in thread stream_worker:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 49, in stream_worker
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.InvalidDataError: [Errno 1094995529] Invalid data found when processing input: 'https://arlostreaming416-z1-prod.wowza.arlo.com:80/stream/[camera-id]_1596631711371.mpd?egressToken=[guid]&userAgent=web&cameraId=[camera-id]_1596631711371&txnId=be![guid]
```

**Comment by twrecked** [comment]
Have you changed your `user_agent`? If you set it to anything other than **apple** you will get `mpeg-dash` streams from Arlo and the stream component doesn't currently support them.

**Comment by ferdyh** [comment]
I have set it to 'linux'

**Comment by twrecked** [comment]
Can you try setting it to `apple`. Or not setting it.

Did it work before or did you change this value recently?

**Comment by ferdyh** [comment]
Hmmm, works when I remove user_agent.

Wouldn't know what worked before, since I'm only setting this up for the first time.

**Comment by twrecked** [comment]
**Short answer:**

Excellent. You don't need to change the `user_agent` unless you want to try direct streaming.

**Long answer:**

So `user_agent` changes the stream type returned from the Arlo servers. For the longest time I would not have recommended setting it because anything other than the default value - `apple` - returns a `rtmps` stream which Home Assistant can't handle.

About 2 weeks ago Arlo changed its streaming mechanism and now setting it to `linux` will return a `https/mpeg-dash` stream. This is great if you only use the custom `aarlo-glance` Lovelace card because you can stream directly from the Arlo servers to the card. But the Home Assistant `stream` component doesn't support `mpeg-dash` which can break some features. So your choices are:

- don't set it and everything should work but you'll use more computing power to translate the stream inside Home Assistant and there will be no audio
- use `linux` and direct streaming in the `aarlo-glance` card and you'll stream directly from Arlo with sound but some internal Home Assistant mechanisms might not work correctly

**Comment by twrecked** [comment]
I'l closing this because it's working.
