### ISSUE TITLE
Error during setup of component aarlo on home-assistant:0.115.5

### ISSUE THREAD

**Issue by ninjazx06** [twrecked/hass-aarlo#318]
2020-09-29 10:26:54 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 208, in setup
    arlo = PyArlo(username=username, password=password,
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 138, in __init__
    self._be = ArloBackEnd(self)
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 44, in __init__
    self._logged_in = self._login()
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 467, in _login
    if not self._auth():
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 352, in _auth
    body = self.auth_post(AUTH_PATH, {'email': self._arlo.cfg.username,
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 618, in auth_post
    return self._request(path, 'POST', params, headers, False, raw, timeout, self._arlo.cfg.auth_host)
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 88, in _request
    body = r.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Works with home-assistant:0.115.3

**Comment by twrecked** [comment]
I'm seeing the same issue here. I'll investigate.

**Comment by halytech** [comment]
I received the same issue but after restarting the server it seemed to
settle down.

**Comment by twrecked** [comment]
Yeah, it seems intermittent - approx 1 in 10 times. I'm just working out why it happens and how best to handle it.

**Comment by halytech** [comment]
I stand corrected. It looks like after reboot my instance dropped back to
115.4, which is probably why it works.

**Comment by robweber** [comment]
I'm not confident the HA version has anything to do with it really. I have two different HA installs (2 locations) both sub HA 115 that were running great up until this morning. Then they both threw this exact same error, reboots don't seem to help. I think Arlo is returning some weird response, hence the JSON error.

**Comment by halytech** [comment]
I agree after review and a few reboots.

**Comment by ninjazx06** [comment]
Hum... after seeing the above messages I also tried switching back to 0.115.5 and am also able to successfully connect.  Thanks for looking into this.

**Comment by twrecked** [comment]
Can you try 0.7.0.beta.5; it has a (possible) fix for this.

**Comment by ninjazx06** [comment]
Just tried try 0.7.0.beta.5 ==> no errors (but as stated earlier the older version started to work too).

**Comment by robweber** [comment]
I tried to do a reboot (on non beta version) to confirm it was still not working _before_ applying the beta patch. Either fortunately or unfortunately things started working again. I tried a few reboots spaced out 10 minutes each. The aarlo component worked fine in each case. Not sure if this will stick permanently or not; perhaps the whole thing was an Arlo side problem?

**Comment by twrecked** [comment]
I think it was definitely on their end but my code should have handled it better. If you want to check if the code triggered look for `attempt` in the logs. You'll see something like:

```
2020-08-10 14:13:03 DEBUG (ArloEventStream) [pyaarlo] login attempt #1
2020-08-10 14:13:04 DEBUG (ArloEventStream) [pyaarlo] login attempt #2
2020-08-10 14:13:05 DEBUG (ArloEventStream) [pyaarlo] login attempt #3 
```

**Comment by grantclem** [comment]
Still getting the following using the following service call; no recordings are saved to the cloud.

`WARNING (MainThread) [custom_components.aarlo.camera] camera.aarlo_alfresco start recording service failed`

![image](https://user-images.githubusercontent.com/30598978/95036465-9832f880-06fa-11eb-82f7-2f1fbe02c7ad.png)

Using the old service (soon to be deprecated) causes the system to freeze and required HA restart.

Current workaround is use of the "camera" domain and saving the media locally.
