### ISSUE TITLE
issue Arlo setup tfa.py report error

### ISSUE THREAD

**Issue by Bastien42** [twrecked/hass-aarlo#343]
hi so followed your guide setup my YAML with my secondary account linked to my principal was wondering if you had any idea what could go wrong here the 2FA i active on the seconde account could it be it ?  

```
Logger: homeassistant.setup
Source: custom_components/aarlo/pyaarlo/tfa.py:49
First occurred: 6:58:29 (1 occurrences)
Last logged: 6:58:29

Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 240, in setup
    arlo = PyArlo(username=username, password=password,
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 143, in __init__
    self._be = ArloBackEnd(self)
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 45, in __init__
    self._logged_in = self._login()
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 479, in _login
    if not self._auth():
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 401, in _auth
    if not tfa.start():
  File "/config/custom_components/aarlo/pyaarlo/tfa.py", line 49, in start
    self._imap = imaplib.IMAP4_SSL(self._arlo.cfg.tfa_host)
  File "/usr/local/lib/python3.8/imaplib.py", line 1297, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/local/lib/python3.8/imaplib.py", line 198, in __init__
    self.open(host, port)
  File "/usr/local/lib/python3.8/imaplib.py", line 1310, in open
    IMAP4.open(self, host, port)
  File "/usr/local/lib/python3.8/imaplib.py", line 303, in open
    self.sock = self._create_socket()
  File "/usr/local/lib/python3.8/imaplib.py", line 1300, in _create_socket
    sock = IMAP4._create_socket(self)
  File "/usr/local/lib/python3.8/imaplib.py", line 293, in _create_socket
    return socket.create_connection((host, self.port))
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
```

**Comment by twrecked** [comment]
Can you paste in your aarlo config? Minus the secret bits of course. My guess is your tfa host name is wrong.

And I should convert this to an error.

**Comment by Bastien42** [comment]
```
aarlo:
  username: ******
  password: *******
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90

camera:
  - platform: aarlo

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding
    - cry
    - connectivity

alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 8

sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature
    - humidity
    - air_quality

light:
  - platform: aarlo

switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    doorbell_silence: True
    siren_volume: 1
    siren_duration: 10
```

**Comment by twrecked** [comment]
Yes. If you have 2FA enabled you'll need to tell it where to go to get the code. You'll need to add these to you config, filling in the values as needed:

```yaml
aarlo:
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.host.com
  tfa_username: your-user-name
  tfa_password: your-imap-password
```

**Comment by Bastien42** [comment]
okay thanks u turned it off like i don't care as it is not the main user thx 👍

**Comment by twrecked** [comment]
I'll close it for now.
