### ISSUE TITLE
Is there a way to disable 2FA in Aarlo?

### ISSUE THREAD

**Issue by hnydell** [twrecked/hass-aarlo#396]
Since it is possible to disable 2FA on my.arlo.com
Profile->Two-Step Verification->Disable

It seems the latest version of aarlo requires use of 2FA_ ?

**Comment by twrecked** [comment]
It should be optional, did you try?

**Comment by hnydell** [comment]
Yes, Im getting these error messages in the log

2021-02-22 18:45:35 ERROR (MainThread) [homeassistant.setup] Setup of aarlo is taking longer than 300 seconds. Startup will proceed without waiting any longer
2021-02-22 18:45:35 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.camera: Unable to set up component.
2021-02-22 18:48:26 ERROR (SyncWorker_4) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2021-02-22 18:48:26 ERROR (SyncWorker_4) [pyaarlo] 2fa startup failed
2021-02-22 18:48:26 ERROR (SyncWorker_4) [custom_components.aarlo] unable to connect to Arlo: attempt=6,sleep=300,error=2fa startup failed
2021-02-22 18:53:27 ERROR (SyncWorker_4) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2021-02-22 18:53:27 ERROR (SyncWorker_4) [pyaarlo] 2fa startup failed
2021-02-22 18:53:27 ERROR (SyncWorker_4) [custom_components.aarlo] unable to connect to Arlo: attempt=7,sleep=300,error=2fa startup failed
2021-02-22 18:58:28 ERROR (SyncWorker_4) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2021-02-22 18:58:28 ERROR (SyncWorker_4) [pyaarlo] 2fa startup failed
2021-02-22 18:58:28 ERROR (SyncWorker_4) [custom_components.aarlo] unable to connect to Arlo: attempt=8,sleep=300,error=2fa startup failed

**Comment by twrecked** [comment]
It should be optional - I swap between an account that has 2FA and an account that doesn't have 2FA all the time. I'll take a look.

**Comment by hnydell** [comment]
no, it immediately starts to print the errors on imap e t c. I.e I have not defined any tfa_nnnn variables in my conf.

Whole log from starting up the HA container (some complaints on netatmo first)
2021-02-22 19:08:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-22 19:08:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for aarlo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-22 19:08:19 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Home Assistant Cloud for netatmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 91, in async_setup_entry
    await config_entry_oauth2_flow.async_get_config_entry_implementation(
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 387, in async_get_config_entry_implementation
    raise ValueError("Implementation not available")
ValueError: Implementation not available
2021-02-22 19:08:19 ERROR (SyncWorker_4) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2021-02-22 19:08:19 ERROR (SyncWorker_4) [pyaarlo] 2fa startup failed
2021-02-22 19:08:19 ERROR (SyncWorker_4) [custom_components.aarlo] unable to connect to Arlo: attempt=1,sleep=15,error=2fa startup failed
2021-02-22 19:08:28 WARNING (MainThread) [homeassistant.setup] Setup of aarlo is taking over 10 seconds.
2021-02-22 19:08:35 ERROR (SyncWorker_4) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2021-02-22 19:08:35 ERROR (SyncWorker_4) [pyaarlo] 2fa startup failed
2021-02-22 19:08:35 ERROR (SyncWorker_4) [custom_components.aarlo] unable to connect to Arlo: attempt=2,sleep=30,error=2fa startup failed
2021-02-22 19:09:06 ERROR (SyncWorker_4) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2021-02-22 19:09:06 ERROR (SyncWorker_4) [pyaarlo] 2fa startup failed


I'm new to this though so may have missed something. My configuration is very basic to start with

aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120

camera:
  - platform: aarlo

**Comment by twrecked** [comment]
I misunderstood the logs, sorry. Can you turn debug logs on:

```yaml
logger:
  default: info
  logs:
    pyaarlo: debug
```
Restart HA and then look in `home-assistant.log`, it should be at the same place as the `configuration.yaml` file. It will have more information.

**Comment by hnydell** [comment]
Yes, with debug enabled I see the log on "need 2FA..."


2021-02-22 19:21:36 DEBUG (SyncWorker_0) [pyaarlo] need 2FA...
2021-02-22 19:21:36 DEBUG (SyncWorker_0) [pyaarlo] getting tfa choices
2021-02-22 19:21:36 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.HACS_REPO
2021-02-22 19:21:36 DEBUG (SyncWorker_0) [pyaarlo] looking for email
2021-02-22 19:21:36 DEBUG (SyncWorker_0) [pyaarlo] 2fa-imap: starting
2021-02-22 19:21:36 ERROR (SyncWorker_0) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2021-02-22 19:21:36 ERROR (SyncWorker_0) [pyaarlo] 2fa startup failed
2021-02-22 19:21:36 DEBUG (SyncWorker_0) [pyaarlo] failed to log in
2021-02-22 19:21:36 DEBUG (ArloMediaDownloader) [pyaarlo] not starting downloader
2021-02-22 19:21:36 ERROR (SyncWorker_0) [custom_components.aarlo] unable to connect to Arlo: attempt=1,sleep=15,error=2fa startup failed
2021-02-22 19:21:37 INFO (MainThread) [custom_components.hacs] <Integration hacs/integration> Registration completed
2021-02-22 19:21:38 INFO (MainThread) [custom_components.hacs] Restore started
2021-02-22 19:21:38 INFO (MainThread) [custom_components.hacs] Restore done
2021-02-22 19:21:38 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.SENSOR
2021-02-22 19:21:38 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.WAITING
2021-02-22 19:21:38 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2021-02-22 19:21:38 INFO (MainThread) [custom_components.hacs] HACS is enabled
2021-02-22 19:21:38 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2021-02-22 19:21:43 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2021-02-22 19:21:43 INFO (MainThread) [custom_components.hacs] setup task HacsSetupTask.CATEGORIES
2021-02-22 19:21:43 INFO (MainThread) [custom_components.hacs] Loading known repositories
2021-02-22 19:21:45 WARNING (MainThread) [homeassistant.setup] Setup of aarlo is taking over 10 seconds.
2021-02-22 19:21:46 INFO (MainThread) [custom_components.hacs] <Integration custom-components/remote_homeassistant> Registration completed
2021-02-22 19:21:51 DEBUG (SyncWorker_0) [pyaarlo] Cfg started
2021-02-22 19:21:51 DEBUG (SyncWorker_0) [pyaarlo] starting
2021-02-22 19:21:51 DEBUG (SyncWorker_0) [pyaarlo] file not read
2021-02-22 19:21:51 DEBUG (SyncWorker_0) [pyaarlo] custom connections 5:10
2021-02-22 19:21:51 DEBUG (SyncWorker_0) [pyaarlo] login attempt #1
2021-02-22 19:21:52 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.RUNNING
2021-02-22 19:21:52 DEBUG (SyncWorker_0) [pyaarlo] need 2FA...
2021-02-22 19:21:52 DEBUG (SyncWorker_0) [pyaarlo] getting tfa choices
2021-02-22 19:21:52 DEBUG (SyncWorker_0) [pyaarlo] looking for email
2021-02-22 19:21:52 DEBUG (SyncWorker_0) [pyaarlo] 2fa-imap: starting
2021-02-22 19:21:52 ERROR (SyncWorker_0) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2021-02-22 19:21:52 ERROR (SyncWorker_0) [pyaarlo] 2fa startup failed
2021-02-22 19:21:52 DEBUG (SyncWorker_0) [pyaarlo] failed to log in
2021-02-22 19:21:52 DEBUG (ArloMediaDownloader) [pyaarlo] not starting downloader
2021-02-22 19:21:52 ERROR (SyncWorker_0) [custom_components.aarlo] unable to connect to Arlo: attempt=2,sleep=30,error=2fa startup failed

**Comment by hnydell** [comment]
Argghhhh. Sorry guys.
I now realized that the single user account on arlo that had _not_ 2FA disabled was the one I tried to use for aarlo on HA..

Closing this one. Thanks for super speedy help

**Comment by twrecked** [comment]
Glad it's working!
