### ISSUE TITLE
Error loading custom_components.aarlo - No module named 'cloudscraper'

### ISSUE THREAD

**Issue by pmoeller001** [twrecked/hass-aarlo#441]
I have installed aarlo on my raspberry pi. Manually I have copied the aarlo directory into the /config/custom_components directory. 
In /config/configuration.yaml I have writen

aarlo:
  username: xxxxxxxxx
  password: xxxxxxxxx
  refresh_devices_every: 2
  stream_timeout: 120

camera:
  - platform: aarlo

When I restarted the home assistant core I got these results:

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:482
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 12:47:18 (1 occurrences)
Last logged: 12:47:18

Component error: aarlo - Integration 'aarlo' not found. Platform error camera.aarlo - Integration 'aarlo' not found.

2021-05-14 12:47:18 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.aarlo. Make sure all dependencies are installed
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 609, in _load_file
module = importlib.import_module(path)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/config/custom_components/aarlo/__init__.py", line 9, in <module>
from .backend import ArloBackEnd
File "/config/custom_components/aarlo/backend.py", line 9, in <module>
import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'
2021-05-14 12:47:18 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.aarlo. Make sure all dependencies are installed
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 609, in _load_file
module = importlib.import_module(path)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/config/custom_components/aarlo/__init__.py", line 9, in <module>
from .backend import ArloBackEnd
File "/config/custom_components/aarlo/backend.py", line 9, in <module>
import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'
2021-05-14 12:47:18 ERROR (MainThread) [homeassistant.components.hassio] Component error: aarlo - Integration 'aarlo' not found.
Platform error camera.aarlo - Integration 'aarlo' not found.

How can I install cloudscraper?
Home Assistant Version core-2021.5.3 
hass-aarlo-0.7.1.beta.14

**Comment by twrecked** [comment]
Is there a `manifest.json` file in `custom_components/aarlo`? It needs to be there to tell Home Assistant to install `cloudscraper`.

**Comment by pmoeller001** [comment]
No, there is no manifest.json file. Where can I get it?

**Comment by twrecked** [comment]
It should be in the source code, under `custom_components/aarlo/`.

**Comment by pmoeller001** [comment]
Now there is  this manifest.json file:
{
  "domain": "aarlo",
  "name": "Arlo Camera Support",
  "documentation": "https://github.com/twrecked/hass-aarlo/blob/master/README.md",
  "issue_tracker": "https://github.com/twrecked/hass-aarlo/issues",
  "dependencies": ["ffmpeg"],
  "codeowners": ["@twrecked"],
  "requirements": ["unidecode","cloudscraper"],
  "version": "0.7.1b14",
  "iot_class": "cloud_push"
}

But errors still occur.

**Comment by twrecked** [comment]
Where is the file? What are its permissions? And did you restart?

It should read the `manifest.json` and install the needed components.

**Comment by pmoeller001** [comment]
Thank you for your answers. I have restarted the Host and now it is o.k.
