### ISSUE TITLE
Invalid config for [aarlo]: required key not provided @ data['aarlo']['password']. Got None

### ISSUE THREAD

**Issue by Reserton** [twrecked/hass-aarlo#466]
I installed aarlo using HACS.

I then edited the config files.

Then trying to restart after adding the relevant configuration I am getting the below errors : 

Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:161
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:24:42 (1 occurrences)
Last logged: 22:24:42

[22933108698224] The system cannot restart because the configuration is not valid: Component error: username - Integration 'username' not found. Invalid config for [aarlo]: required key not provided @ data['aarlo']['password']. Got None required key not provided @ data['aarlo']['username']. Got None. (See ?, line ?). Component error: password - Integration 'password' not found.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 728, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 161, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: username - Integration 'username' not found.
Invalid config for [aarlo]: required key not provided @ data['aarlo']['password']. Got None
required key not provided @ data['aarlo']['username']. Got None. (See ?, line ?). 
Component error: password - Integration 'password' not found.

My Config file has the following : 

aarlo:
username: !secret arlo_username
password: !secret arlo_password

camera:
- platform: aarlo

and my secrets file has the relevant arlo_username and arlo_password with my actual username and password.

**Comment by twrecked** [comment]
Can you paste the config in inside triple backticks (see [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))? I think you are missing the spaces before the username and password but can't tell from your bug report.

**Comment by Reserton** [comment]
My bad, you were right.

I originally got tons of errors about bad /t which googling was about tabs. so I removed the spaces and then the error went away and this new error appeared.

I deleted everything in config and started again and now its working great.

Thanks for help.
