### ISSUE TITLE
AttributeError: module 'cloudscraper' has no attribute 'create_scraper'

### ISSUE THREAD

**Issue by damaroberts** [twrecked/hass-aarlo#525]
I am having trouble setting up aarlo.  Im getting the message below in the logs.  Any help appreciated.

2021-11-23 21:26:50 ERROR (MainThread) [homeassistant.setup] Error during setup of component aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
    result = await task
  File "/config/custom_components/aarlo/__init__.py", line 248, in async_setup
    arlo = await hass.async_add_executor_job(login, hass, conf)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 380, in login
    arlo = PyArlo(
  File "/usr/local/lib/python3.9/site-packages/pyaarlo/__init__.py", line 160, in __init__
    self._be = ArloBackEnd(self)
  File "/usr/local/lib/python3.9/site-packages/pyaarlo/backend.py", line 64, in __init__
    self._logged_in = self._login()
  File "/usr/local/lib/python3.9/site-packages/pyaarlo/backend.py", line 682, in _login
    self._session = cloudscraper.create_scraper()
AttributeError: module 'cloudscraper' has no attribute 'create_scraper'

**Comment by twrecked** [comment]
I'll have a look. That's a 3rd party module that should be brought in automatically.

**Comment by damaroberts** [comment]
This now appears to be an issue with my system configuration.  Importing the same configuration into a standard home assistant OS (with supervisor) raises no issues.  I was having issues with home assistant supervisor installed on ubuntu.  Assuming depencies were not being brought in correctly.  Suggest defect can be closed.
