### ISSUE TITLE
error if taking snapshot or stream with master branch

### ISSUE THREAD

**Issue by maheus** [twrecked/hass-aarlo#73]
Hi @twrecked , i have a new error with HA 0.94.3 and python 3.7. Do you have an idea ?

```
2019-06-13 15:46:44 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1218843184] Error handling message: Unknown error
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/camera.py", line 383, in websocket_snapshot_image
    image = await camera.async_get_snapshot()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/camera.py", line 301, in get_snapshot
    return self._camera.get_snapshot()
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/pyaarlo/camera.py", line 397, in get_snapshot
    self._request_snapshot()
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/pyaarlo/camera.py", line 384, in _request_snapshot
    self.take_idle_snapshot()
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/pyaarlo/camera.py", line 372, in take_idle_snapshot
    'to': self.parent_id,
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/pyaarlo/device.py", line 166, in parent_id
    if self._parentId is not None:
AttributeError: 'ArloCamera' object has no attribute '_parentId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/decorators.py", line 17, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/homeassistant/.homeassistant/custom_components/aarlo/camera.py", line 391, in websocket_snapshot_image
    except HomeAssistantError:
NameError: name 'HomeAssistantError' is not defined
```

**Comment by twrecked** [comment]
That'll be me! Give me a few minutes...

**Comment by twrecked** [comment]
Can you update and try again. I introduced a silly typo.

**Comment by maheus** [comment]
perfect, thanks
