### ISSUE TITLE
camera_request_video_to_file service not work: TypeError: a bytes-like object is required, not 'NoneType'

### ISSUE THREAD

**Issue by StefanoGithubHA** [twrecked/hass-aarlo#731]
Hi,
I've an issue with camera_request_video_to_file service. I configured yaml file and I created an automation runs the service.

part of yaml file:
......
action:
      - service: aarlo.camera_request_video_to_file
        data:
          entity_id: camera.aarlo_study_room_camera
          filename: aarlo/study_room_camera/pippo.mp4
......

 aarlo/study_room_camera/ path has all permission (rwx).

When the automation is triggered I get follow error:

TypeError: a bytes-like object is required, not 'NoneType'
2023-03-13 15:26:00.389 ERROR (MainThread) [homeassistant.components.automation.arlo_trigger_di_prova] While executing automation automation.arlo_trigger_di_prova
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 545, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/aarlo/camera.py", line 226, in async_service_callback
    await hass.async_add_executor_job(service_callback, call)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/camera.py", line 217, in service_callback
    camera_video_to_file_service(hass, call)
  File "/config/custom_components/aarlo/camera.py", line 996, in camera_video_to_file_service
    out_file.write(video)

If it can help, I noticed that "camera" object in camera.py file is None and get_video() method return a None object (view 996 line).

Thanks for your help.
Stefano

**Comment by twrecked** [comment]
Let me look, it's been a while since I played around with that service.

**Comment by StefanoGithubHA** [comment]
Ok. Thanks very much for your interest.

**Comment by RNiveau** [comment]
Do you have any update on this ? I have the same issue
