### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by pesce** [twrecked/hass-aarlo#746]
Hello, recently after a HA update, I began experiencing this error which prevents aarlo from loading.  Any ideas?  Thank you in advance!  And thank you for the development. 

aarlo Component Setup
Error: general-error=SSLCertVerificationError
Traceback (most recent call last):
File "/config/custom_components/aarlo/pyaarlo/backend.py", line 485, in _mqtt_main
self._event_client.connect(MQTT_HOST, port=443, keepalive=60)
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1073, in reconnect
sock.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mqtt-cluster.arloxcld.com'. (_ssl.c:1007)

**Comment by Ghjalle** [comment]
Having the same issue. updated everything and not working. Im using the push notification from arlo app and it says that another user is logged in.
