### ISSUE TITLE
aarlo Component Setup Issue

### ISSUE THREAD

**Issue by riddledaxis** [twrecked/hass-aarlo#758]
Hi,

I am running the latest version of Home Assistant and HACS and have tried to setup up aarlo v0.7.4b12 and I am havoing a really weird issue.

I had aarlo working in another Home Assitant server but I am struggling to get it working on this new server.

The issue is this - 

Error: general-error=SSLCertVerificationError
Traceback (most recent call last):
File "/config/custom_components/aarlo/pyaarlo/backend.py", line 490, in _mqtt_main
self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1073, in reconnect
sock.do_handshake()
File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mqtt-cluster.arloxcld.com'. (_ssl.c:1007)

This error just keeps repeating over and over when in Debug mode.
I am confused as to wether this is my MQTT it is trying to connect to or another server?

My system is as follows:
Home Assistant - 2023.5.4
Supervisor - 2023.04.1
OS - 10.2
Frontend 20230503.03 - latest

Any idea what is happening?

Thanks

Paul

**Comment by togild** [comment]
https://github.com/twrecked/hass-aarlo/releases/tag/v0.7.4b12

"If you use the mqtt back end and see certificate issues you can try adding one of these to your Aarlo configuration:

add mqtt_hostname_check: False, this stops certificate validation. The downside here is any one can potentially now pretend to be Arlo.
add mqtt_host: mqtt-cluster-z1.arloxcld.com, this changes the MQTT host we use to a fixed one, the certificate on this host is correct. The downside here is they could remove this host at any time
I've added a third option, mqtt_transport this defaults to tcp and you shouldn't need to change it. The only other value it can be is websockets."

**Comment by riddledaxis** [comment]
The fix for me was to add backend: sse to my aarlo config and then reboot the HA server.

Thanks for your quick response @togild  

> https://github.com/twrecked/hass-aarlo/releases/tag/v0.7.4b12
> 
> "If you use the mqtt back end and see certificate issues you can try adding one of these to your Aarlo configuration:
> 
> add mqtt_hostname_check: False, this stops certificate validation. The downside here is any one can potentially now pretend to be Arlo. add mqtt_host: mqtt-cluster-z1.arloxcld.com, this changes the MQTT host we use to a fixed one, the certificate on this host is correct. The downside here is they could remove this host at any time I've added a third option, mqtt_transport this defaults to tcp and you shouldn't need to change it. The only other value it can be is websockets."

Thanks for your quick response @togild  

But the fix for me was to add backend: sse to my aarlo config and then reboot the HA server.
