### ISSUE TITLE
Integration Not Loading As Of 2023-06-01

### ISSUE THREAD

**Issue by jpreiditsch** [twrecked/hass-aarlo#759]
I'm assuming that Arlo has made additional changers. After my nightly HA restart Aarlo no longer worked. Attempted restarts 8 hours later did not resolve the issue

Home Assistant Version 2023.5.4
Aarlo Version (From HACS) 0.7.4b12

The following messages showed up in my home assistant notifications
aarlo Component Setup
Error: unable to read mode, try forcing v2
If error persists you might need to change config and restart.

The following integrations and platforms could not be set up:

aarlo.alarm_control_panel ([Show logs](http://hassio.local:8123/config/logs?filter=aarlo.alarm_control_panel))
aarlo.camera ([Show logs](http://hassio.local:8123/config/logs?filter=aarlo.camera))
Please check your config and [logs](http://hassio.local:8123/config/logs).

The following lines appear to be relevant in the debug logs

2023-06-01 08:49:50.909 DEBUG (ArloEventStream) [pyaarlo] mqtt: host=mqtt-cluster.arloxcld.com, check=False, transport=tcp
2023-06-01 08:49:50.912 ERROR (ArloEventStream) [pyaarlo] general-error=gaierror
Traceback (most recent call last):
  File "/config/custom_components/aarlo/pyaarlo/backend.py", line 490, in _mqtt_main
    self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

2023-06-01 08:50:23.060 ERROR (ArloBackgroundWorker) [pyaarlo] unable to read mode, try forcing v2

**Comment by twrecked** [comment]
They've changed (or removed) their `mqtt` servers, can you try the `sse` backend.

**Comment by jpreiditsch** [comment]
Thanks for the quick response, switching over to sse fixed the issue.

**Comment by twrecked** [comment]
https://github.com/twrecked/hass-aarlo#missing-events

Add this to you config.

**Comment by jr-air** [comment]
That fixed it. Many Thanks.

(Didn't see this setting in the v0.7 branch readme, but worked for the HACS supported version)

**Comment by vituzzo77** [comment]
mqtt-cluster.arloxcld.com was switched to mqtt-cluster-z1-new-ext-944ca53bc9be2a3c.elb.eu-west-1.amazonaws.com on 2023-05-27 but you can still continue using the mqtt backend by changing this value in the constant.py
