### ISSUE TITLE
Error: 2fa startAuth failed If error persists you might need to change config and restart.

### ISSUE THREAD

**Issue by TORCHEBUGNE** [twrecked/hass-aarlo#768]
Here is the translation:

"I haven't made any updates, but for the past few days, my aarlo integration stopped working. I'm receiving this error message: aarlo Component Setup Error: 2fa startAuth failed. If the error persists, you might need to change the configuration and restart. 

and 

Invalid config
The following integrations and platforms could not be set up:

aarlo (Show logs)
aarlo.binary_sensor (Show logs)
aarlo.sensor (Show logs)
aarlo.light (Show logs)
aarlo.alarm_control_panel (Show logs)
aarlo.media_player (Show logs)
aarlo.camera (Show logs)
aarlo.switch (Show logs)
Please check your config and logs.

Here's my configuration:########aarlo#######
aarlo:
  username: xxxxxxxxxxx
  password: xxxxxxxxxx
  backend: sse
  tfa_source: push
  tfa_type: push
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 8
camera:
  - platform: aarlo
binary_sensor:
  - platform: aarlo
    monitored_conditions:
      - motion
      - sound
      - ding
      - cry
      - connectivity
sensor:
  - platform: aarlo
    monitored_conditions:
      - total_cameras
      - last_capture
      - recent_activity
      - captured_today
      - battery_level
      - signal_strength
      - temperature
      - humidity
      - air_quality
light:
  - platform: aarlo
media_player:
  - platform: aarlo"

Do you have a solution?

**Comment by ghostsam45** [comment]
same issue

Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:495
Integration: aarlo ([documentation](https://github.com/twrecked/hass-aarlo/blob/master/README.md), [issues](https://github.com/twrecked/hass-aarlo/issues))
First occurred: 07:43:27 (4 occurrences)
Last logged: 07:45:15

unable to connect to Arlo: attempt=1,sleep=15,error=2fa startAuth failed
unable to connect to Arlo: attempt=2,sleep=30,error=2fa startAuth failed
unable to connect to Arlo: attempt=3,sleep=60,error=2fa startAuth failed
unable to connect to Arlo: attempt=4,sleep=120,error=2fa startAuth failed

**Comment by septeven** [comment]
same here, everything stopped working in the last two days...

**Comment by twrecked** [comment]
Can you see if anything in here helps: https://github.com/twrecked/hass-aarlo/issues/762

It's probably a cloud flare issue.

**Comment by ninjazx06** [comment]
I started to get authentication error in my Arlo integration this morning.  I tried upgrading to hass-aarlo-0.7.4b16 and downgrading to hass-aarlo-0.7.4b12 and same errors.

2023-07-02 10:55:12.406 WARNING (SyncWorker_2) [pyaarlo] body-error=JSONDecodeError
2023-07-02 10:55:13.468 WARNING (SyncWorker_2) [pyaarlo] body-error=JSONDecodeError
2023-07-02 10:55:14.536 WARNING (SyncWorker_2) [pyaarlo] body-error=JSONDecodeError
2023-07-02 10:55:15.542 ERROR (SyncWorker_2) [pyaarlo] authentication failed
2023-07-02 10:55:15.587 ERROR (SyncWorker_2) [custom_components.aarlo] unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
2023-07-02 10:55:22.289 WARNING (MainThread) [homeassistant.setup] Setup of aarlo is taking over 10 seconds.
2023-07-02 10:55:30.703 WARNING (SyncWorker_2) [pyaarlo] body-error=JSONDecodeError
2023-07-02 10:55:31.718 WARNING (SyncWorker_2) [pyaarlo] body-error=JSONDecodeError
2023-07-02 10:55:32.733 WARNING (SyncWorker_2) [pyaarlo] body-error=JSONDecodeError
2023-07-02 10:55:33.734 ERROR (SyncWorker_2) [pyaarlo] authentication failed
2023-07-02 10:55:33.739 ERROR (SyncWorker_2) [custom_components.aarlo] unable to connect to Arlo: attempt=2,sleep=30,error=authentication failed
2023-07-02 10:56:03.844 WARNING (SyncWorker_2) [pyaarlo] body-error=JSONDecodeError
2023-07-02 10:56:04.858 WARNING (SyncWorker_2) [pyaarlo] body-error=JSONDecodeError
2023-07-02 10:56:05.873 WARNING (SyncWorker_2) [pyaarlo] body-error=JSONDecodeError
2023-07-02 10:56:06.874 ERROR (SyncWorker_2) [pyaarlo] authentication failed
2023-07-02 10:56:06.888 ERROR (SyncWorker_2) [custom_components.aarlo] unable to connect to Arlo: attempt=3,sleep=60,error=authentication failed

**Comment by twrecked** [comment]
I think they change something on the backend again, a user on the pyaarlo repository might have found the solution. I'm looking at it.

**Comment by Avatar1976** [comment]
> I think they change something on the backend again, a user on the pyaarlo repository might have found the solution. I'm looking at it.

Thanks Twrecked!

**Comment by Phoenix-DH** [comment]
Same for me, no version is working!

Thanks for your work.

**Comment by twrecked** [comment]
I'll try and get something out later but two things are happening to me:

- I need updated cache header settings
- cloudscraper is not playing well with the sse channel

**Comment by JCvanDoorn** [comment]
I have the same issue with multiple versions as well.
unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed

I've also tried to use the "backend" option with both sse and mqtt, but neither solve my issue.

**Comment by Phoenix-DH** [comment]
I was moving beginning from march from homebridge to home assistant.

I am wondering if they have the same issues:
https://github.com/homebridge-plugins/homebridge-arlo

**Comment by Phoenix-DH** [comment]
B17 same issue, I also deleted the session.pickle file.
The error really quickly occurs after restart.

**Comment by dannysporea** [comment]
Getting this error after deleting session.pickle and restart...

Error: general-error=gaierror
Traceback (most recent call last):
File "/config/custom_components/aarlo/pyaarlo/backend.py", line 497, in _mqtt_main
self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 827, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name does not resolve

If error persists you might need to change config and restart.

**Comment by twrecked** [comment]
@dannysporea change your backend to sse, add this to your config:

```yaml
aarlo:
  backend: sse
```

But that does look like you managed to log in.

@Phoenix-DH  Good question about home-bridge, and I don't have an answer. I read somewhere this issues happens because of the Python request library, but I'm not really sure about that either. I do know it's annoying.

I'll try and add some more debug to a build later but if anyone is good with an editor can you turn on debug? In `custom_components/aarlo/pyaarlo/backend.py` on line 854, add `debug=True` to the `create_scraper` call. Like this:

```
            self._session = cloudscraper.create_scraper(debug=True)
```

**Comment by Phoenix-DH** [comment]
Great, thanks!
Btw I got also added sse without success

**Comment by Bastien42** [comment]
> @dannysporea change your backend to sse, add this to your config:
> 
> ```yaml
> aarlo:
>   backend: sse
> ```
> 
> But that does look like you managed to log in.
> 
> @Phoenix-DH Good question about home-bridge, and I don't have an answer. I read somewhere this issues happens because of the Python request library, but I'm not really sure about that either. I do know it's annoying.
> 
> I'll try and add some more debug to a build later but if anyone is good with an editor can you turn on debug? In `custom_components/aarlo/pyaarlo/backend.py` on line 854, add `debug=True` to the `create_scraper` call. Like this:
> 
> ```
>             self._session = cloudscraper.create_scraper(debug=True)
> ```

done that and restarted HA can't see anything in the log though 



```
2023-07-04 22:31:08.439 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 55 and 106
2023-07-04 22:31:08.439 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "homeassistant". Check lines 82 and 129
2023-07-04 22:31:08.497 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration bambu_lab which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-04 22:31:08.498 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_gateway3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-04 22:31:08.498 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-04 22:31:08.498 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration cover_rf_time_based which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-04 22:31:08.499 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-04 22:31:08.499 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration aarlo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-04 22:31:08.499 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration meross_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-04 22:31:08.500 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration enphase_envoy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-04 22:31:08.500 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration meross_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-04 22:31:12.516 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:31:12.564 ERROR (MainThread) [homeassistant.setup] The tuya integration does not support YAML setup, please remove it from your configuration
2023-07-04 22:31:12.626 WARNING (MainThread) [homeassistant.components.meteo_france] 1 hour rain forecast not available. Saint-Priest-en-Jarez - Rhône-Alpes (42) - FR is not in covered zone
2023-07-04 22:31:13.063 WARNING (MainThread) [homeassistant.components.vesync.fan] humidifier - Unknown device type - Classic300S
2023-07-04 22:31:13.070 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(Entertainment): incorrect timestamp: -10 seconds behind HA
2023-07-04 22:31:13.073 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(Mosquito plug): incorrect timestamp: -10 seconds behind HA
2023-07-04 22:31:13.075 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(Networking): incorrect timestamp: -10 seconds behind HA
2023-07-04 22:31:13.076 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(Right Terrarium): incorrect timestamp: -10 seconds behind HA
2023-07-04 22:31:13.076 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(Left Terrarium): incorrect timestamp: -10 seconds behind HA
2023-07-04 22:31:13.101 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(Computers): incorrect timestamp: -10 seconds behind HA
2023-07-04 22:31:13.545 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:31:14.562 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:31:15.563 ERROR (SyncWorker_5) [pyaarlo] authentication failed
2023-07-04 22:31:15.565 ERROR (SyncWorker_5) [custom_components.aarlo] unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
2023-07-04 22:31:22.280 WARNING (MainThread) [homeassistant.setup] Setup of aarlo is taking over 10 seconds.
2023-07-04 22:31:30.655 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:31:31.676 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:31:32.698 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:31:33.698 ERROR (SyncWorker_5) [pyaarlo] authentication failed
2023-07-04 22:31:33.701 ERROR (SyncWorker_5) [custom_components.aarlo] unable to connect to Arlo: attempt=2,sleep=30,error=authentication failed
2023-07-04 22:32:03.779 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:32:04.799 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:32:05.817 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:32:06.818 ERROR (SyncWorker_5) [pyaarlo] authentication failed
2023-07-04 22:32:06.819 ERROR (SyncWorker_5) [custom_components.aarlo] unable to connect to Arlo: attempt=3,sleep=60,error=authentication failed
2023-07-04 22:32:09.992 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: aarlo
2023-07-04 22:33:06.911 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:33:07.934 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:33:08.951 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2023-07-04 22:33:09.952 ERROR (SyncWorker_5) [pyaarlo] authentication failed
2023-07-04 22:33:09.954 ERROR (SyncWorker_5) [custom_components.aarlo] unable to connect to Arlo: attempt=4,sleep=120,error=authentication failed
2023-07-04 22:33:09.954 ERROR (SyncWorker_5) [custom_components.aarlo] unable to connect to Arlo: stopping retries, too may failures
2023-07-04 22:33:09.954 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration aarlo: Integration failed to initialize.
2023-07-04 22:33:09.957 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.camera: Unable to set up component.
2023-07-04 22:33:09.959 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.light: Unable to set up component.
2023-07-04 22:33:09.959 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.binary_sensor: Unable to set up component.
2023-07-04 22:33:09.959 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.alarm_control_panel: Unable to set up component.
2023-07-04 22:33:09.960 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform aarlo.switch: Unable to set up component.
2023-07-04 22:33:09.965 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.current_energy_exporting (<class 'homeassistant.components.template.sensor.SensorTemplate'>) is using native unit of measurement 'W' which is not a valid unit for the device class ('energy') it is using; expected one of ['GJ', 'MWh', 'MJ', 'kWh', 'Wh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22
2023-07-04 22:33:09.972 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.current_energy_importing (<class 'homeassistant.components.template.sensor.SensorTemplate'>) is using native unit of measurement 'W' which is not a valid unit for the device class ('energy') it is using; expected one of ['GJ', 'MWh', 'MJ', 'kWh', 'Wh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22
2023-07-04 22:33:09.993 WARNING (MainThread) [homeassistant.components.netatmo] Webhook not registered - https and port 443 is required to register the webhook

```


![image](https://github.com/twrecked/hass-aarlo/assets/37946663/76abdde0-720e-47ea-965e-802be379cea5)

**Comment by Bastien42** [comment]
wait version 0.7.4.beta.17 worked for note that i also deleted session.pickle file and it just went through

**Comment by septeven** [comment]
Hello,
After a few days working well using v12, it broke this morning. I spent the whole day trying to uninstall - reinstall, trying with v12 then v16 and latest v17, etc. Nothing works, the aarlo component won't start, forcing HA to stop trying.

I notice this warning, note that I'm still able to login to my arlo with my credentials : 
```
error in new response={'meta': {'code': 401, 'error': 9015, 'message': 'Password not correct'}}
authentication failed
error in new response={'meta': {'code': 403, 'error': 9017, 'message': 'Account locked'}}
body-error=JSONDecodeError
```

**Comment by twrecked** [comment]
@Bastien42 It's working now? And the logging in cloud scraper is annoying, it goes to `stdout`. I didn't realise this until I tried my change, the only way to see it is from the docker logs.

`docker logs <container-name> 2>/dev/null`

@septeven Did you delete `.aarlo/session.pickle`?

**Comment by Bastien42** [comment]
> @Bastien42 It's working now? And the logging in cloud scraper is annoying, it goes to `stdout`. I didn't realise this until I tried my change, the only way to see it is from the docker logs.
> 
> `docker logs <container-name> 2>/dev/null`
> 
> @septeven Did you delete `.aarlo/session.pickle`?

i mean i could but it just works now for me kinda don't want to delete the token now in case it was a fluke

**Comment by twrecked** [comment]
Agreed, If it's working, leave it well alone :)

**Comment by septeven** [comment]
> @Bastien42 It's working now? And the logging in cloud scraper is annoying, it goes to `stdout`. I didn't realise this until I tried my change, the only way to see it is from the docker logs.
> 
> `docker logs <container-name> 2>/dev/null`
> 
> @septeven Did you delete `.aarlo/session.pickle`?

Yes multiple times, still having the same errors, the component not loading, no 2FA request on my phone.
Note my config, in case I should change something here ? :
```yaml
aarlo:
  username: !secret arlo_usr
  password: !secret arlo_pwd
  tfa_source: push
  tfa_type: PUSH
  last_format: '%d/%m/%Y %H:%M:%S %a'
  backend: sse
```

**Comment by twrecked** [comment]
@septeven Can you turn on and capture some [debug](https://github.com/twrecked/hass-aarlo#basic-debug) - I'd go straight to verbose level. And [encrypt] it and attach it here.

**Comment by septeven** [comment]
Here it is, let me know if you need something else :
[encrypted_logs.txt](https://github.com/twrecked/hass-aarlo/files/11952356/encrypted_logs.txt)

**Comment by twrecked** [comment]
You're seeing the cloudflare issue. Ca n you turn on verbose debug and try again?

```yaml
aarlo:
  verbose_debug: True
```

**Comment by imcass** [comment]
Hi! Having issues since today as well. (error=authentication failed)

I tried the following:

1. Installed the latest v0.7.4b17, same error as before
2. Change backend to `sse` manually in config. Didn't work 
3. Manually deleted the `.aarlo/session.pickle` file. Didn't work (same error) and the system did not recreate the file, I assumed it would
4. Based on 2 above, decided to entirely remove and install the integration from scratch. Did not work, same error and again only the `aarlo.pickle` was created, the `.aarlo/session.pickle` was never created

My config looks like the following:

```
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret tfa_username
  tfa_password: !secret tfa_password
```

Would appreciate some help, thanks!

**Comment by pesce** [comment]
Updating to v0.7.4b17 worked for me.

**Comment by twrecked** [comment]
@imcass You're seeing the cloudflare issue, they are rejecting your connection, that's why the pickle file didn't come back, there was no successful login made.

If you're running b17 then maybe try again in a few hours or reconnect to your ISP if that changes your IP address.

**Comment by ninjazx06** [comment]
Good new/Bad news for me.
Good news ==> with b17 I am no longer getting authentication errors.  I looks to be successfully logged in and reading Arlo status correct.
Bad news ==> is I am not able to set Arlo status via Home Assistance.  I think it might be this issue https://github.com/twrecked/hass-aarlo/issues/767.  I will log my error there.

Also wanted to relay my appreciation of all the work here - Thank you!

**Comment by Phoenix-DH** [comment]
I just rebootet my Arlo and tried again - it was working now!
Don't know if that was the issue ....

And what I was wondering ... the 2FA Push was comming on my iPad app, not on the iPhone one (for both I have the same account).

**Comment by septeven** [comment]
> You're seeing the cloudflare issue. Ca n you turn on verbose debug and try again?
> 
> ```yaml
> aarlo:
>   verbose_debug: True
> ```

Please see attached, thanks :
[home-assistant_2023-07-05T06-14-00.811Z-encrypted.log](https://github.com/twrecked/hass-aarlo/files/11954453/home-assistant_2023-07-05T06-14-00.811Z-encrypted.log)

**Comment by feron81** [comment]
This morning I my Arlo Integration doesn't works anymore. Yesterday, I had no problem.  I changed nothing (no HA Update, no Arlo Update). I get following errors "Invalid config" and "aarlo Component setup Error: authentication failed". I integrated backend:sse already, but that's not the solution. Does everyone has the an idea, what could be the problem?

**Comment by Avatar1976** [comment]
Version b17 fixed Twrecked, love your work buddy ❤️

**Comment by bjorrwahman** [comment]
@twrecked Thank you for your hard work, I had auth problems and your latest fixes sorted it out and its working again.

**Comment by feron81** [comment]
I still have the same error also with Version b17. Yesterday everything worked, this morning authentication errors like my post before. This are my settings in the configuration.yaml. What could be the problem?

aarlo:
  username: test@text.com
  password: sdfaffsd
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.mail.me.com:993
  tfa_username: test@me.com
  tfa_password: test-test-test-test
  backend: sse

**Comment by niko-nylander** [comment]
Same here.

**Comment by JCvanDoorn** [comment]
Same here.

**Comment by niko-nylander** [comment]
I got it working now. I just reboot Arlo, reboot Home Assistant and download again b17 version.

**Comment by JCvanDoorn** [comment]
By Reboot Arlo, do you mean reboot the Arlo Hub that I have?

**Comment by niko-nylander** [comment]
> By Reboot Arlo, do you mean reboot the Arlo Hub that I have?

Yes, I meant Arlo hub.

**Comment by feron81** [comment]
The same for me, after camera reboot, download b17 again and reboot Home assistant it works. Thank you very much for your help

**Comment by imcass** [comment]
I must be really unlucky.

> @imcass You're seeing the cloudflare issue, they are rejecting your connection, that's why the pickle file didn't come back, there was no successful login made.
> 
> If you're running b17 then maybe try again in a few hours or reconnect to your ISP if that changes your IP address.

Tried the above, didn't work (12h after I tried it last night)


> I got it working now. I just reboot Arlo, download again b17 version and reboot Home Assistant.

Tried this as well, also didn't work. :(

**Comment by sological** [comment]
My logs shows stuff about cookies. Snippet from debug log:

```
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->


</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> ocapi-app.arlo.com</h2>
      </div><!-- /.header -->
```

**Comment by Phoenix-DH** [comment]
Mine stopped also again after it worked with b17:

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:712 
Integration: Arlo Camera Support ([documentation](https://github.com/twrecked/hass-aarlo/blob/master/README.md), [issues](https://github.com/twrecked/hass-aarlo/issues)) 
First occurred: July 5, 2023 at 5:21:36 PM (5 occurrences) 
Last logged: 6:02:25 AM

Failed to set mode.

**Comment by niko-nylander** [comment]
> > By Reboot Arlo, do you mean reboot the Arlo Hub that I have?
> 
> Yes, I meant Arlo hub.

I got everything else work, but Arm<>Disarm the alarm doesn't work.
I saw that there is now two services in HA 2023.7.0 versio.
- aarlo.alarm_set_mode
- alarm_control_panel.aarlo_set_mode

but neither works.

**Comment by Phoenix-DH** [comment]
I wan‘t also to check, but I lost aarlo completely…

So if you are not able to change state, avoid restart.

**Comment by tudora2** [comment]
Hi, 

The error I've got since yesterday is: 
"Error executing the script. Service not found for call_service at pos 1: Unable to find service alarm_control_panel.aarlo_set_mode" 

This automation worked flawlessly for a year or so. Tried to find the service (alarm_control_panel.aarlo_set_mode) under "Developer Tools" -> "Services" but had no success, it is not listed there anymore.

Rolled back to a previous backup( two days ago), and installed again the Aarlo b17 version but no luck.
Tried both "aarlo.alarm_set_mode" and  "alarm_control_panel.aarlo_set_mode" in my automation (the last one worked until yesterday) but again no joy.
When I restart HA (2023.7.0 latest one ) I got the following notifications:

1. Invalid config
The following integrations and platforms could not be set up:
aarlo.binary_sensor ([Show logs](http://*****/config/logs?filter=aarlo.binary_sensor))
aarlo.sensor ([Show logs](http://*****/config/logs?filter=aarlo.sensor))
aarlo.camera ([Show logs](http://******/config/logs?filter=aarlo.camera))
aarlo.alarm_control_panel ([Show logs](http://******/config/logs?filter=aarlo.alarm_control_panel))
Please check your config and [logs](http://******/config/logs).

2. aarlo Component Setup
Error: authentication failed
If error persists you might need to change config and restart.

I'm 110% sure my login details are ok (tested on my phone) so it is not a username/password issue.
The below is the aarlo bit in my configuration.yaml file:

aarlo:
  username: *****
  password: *****
  refresh_devices_every: .5
  stream_timeout: 120
  tfa_source: 'imap'
  tfa_type: 'email'
  tfa_host: 'imap.gmail.com:993'
  tfa_username: *****
  tfa_password: ******
  reconnect_every: 2
  request_timeout: 120
  user_agent: linux
  mode_api: auto
  backend: sse
camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
binary_sensor:
  - platform: aarlo
    monitored_conditions:
      - motion


alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 8

And the automation that causes the issue:

alias: CCTV Schedule 
trigger:
  platform: time_pattern
  minutes: /1
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: device_tracker.****
      state: 'home'
    - condition: state
      entity_id: device_tracker.*****
      state: 'home'
action:
  - service:  alarm_control_panel.aarlo_set_mode
    data:
     entity_id: alarm_control_panel.aarlo_******
     mode: >
      {% if now().hour | int > 5 and  now().hour | int < 22 %} DayTime
      {% else %} NightTime
      {% endif %}


Any hint or tip will be very much appreciated. I really need this automation to work.
Thank you

**Comment by niko-nylander** [comment]
> > > By Reboot Arlo, do you mean reboot the Arlo Hub that I have?
> > 
> > 
> > Yes, I meant Arlo hub.
> 
> I got everything else work, but Arm<>Disarm the alarm doesn't work on HA. Arlo app that works and state update to HA. I saw that there is now two services in HA 2023.7.0 versio.
> 
> * aarlo.alarm_set_mode
> * alarm_control_panel.aarlo_set_mode
> 
> but neither works.
> 
> Logger: pyaarlo Source: custom_components/aarlo/pyaarlo/**init**.py:712 Integration: Arlo Camera Support (documentation, issues) First occurred: 10.07.53 (24 occurrences) Last logged: 11.02.37
> 
> Failed to set mode.

I got everything working on version b18 and HA version 2023.7.1

**Comment by JCvanDoorn** [comment]
Did you do anything in particular. I'm still getting the same errors (unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed) with b18 and 2023.7.1

**Comment by imcass** [comment]
v0.7.4b18 fixed the integration for me, but I need to have `mqtt_host: mqtt-cluster-z1.arloxcld.com` added to my config. As soon as I remove it my logs throw a bunch of errors.

```
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret tfa_username
  tfa_password: !secret tfa_password
  mqtt_host: mqtt-cluster-z1.arloxcld.com
```

**Comment by Phoenix-DH** [comment]
I tried now all allready mentioned posibilities from all the threads… still no chance…

**Comment by tudora2** [comment]
Same here. Still get the:
Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:495
Integration: aarlo ([documentation](https://github.com/twrecked/hass-aarlo/blob/master/README.md), [issues](https://github.com/twrecked/hass-aarlo/issues))
First occurred: 14:15:29 (4 occurrences)
Last logged: 14:17:24

unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
unable to connect to Arlo: attempt=2,sleep=30,error=authentication failed
unable to connect to Arlo: attempt=3,sleep=60,error=authentication failed
unable to connect to Arlo: attempt=4,sleep=120,error=authentication failed

**Comment by PIXLhunter** [comment]
Did you ever get this issue resolved?
