### ISSUE TITLE
Error when starting Home Assistant

### ISSUE THREAD

**Issue by LeightonSolo** [twrecked/hass-aarlo#793]
I get the TFA request on my device and approve it, but I still end up with this result. Any ideas what the issue could be on my end or is this a bug?

My config.yaml is the following:

aarlo:
  username: email@email.com
  password: password
  tfa_source: push
  tfa_type: PUSH

  
camera:
  - platform: aarlo
    ffmpeg_arguments: "-pred 1 -q:v 2"

HA ERROR:

Error: general-error=gaierror
Traceback (most recent call last):
File "/config/custom_components/aarlo/pyaarlo/backend.py", line 497, in _mqtt_main
self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 827, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name does not resolve

If error persists you might need to change config and restart

**Comment by segaura** [comment]
My best guess you are running in the mqtt server certificate setup summer update by Arlo. Get the latest component version and checkout the release notes, necessarily not skipping [v18 one](https://github.com/twrecked/hass-aarlo/releases/tag/v0.7.4b18) ...in my case setting mqtt_host solved and if you read #778 you find other struggling with the same issue.

**Comment by blackequine** [comment]
For me the problem was in the constant file of the pyaarlo package.  It would appear that the MQTT_HOST name has changed from "mqtt-cluster.arloxcld.com" to "mqtt-cluster-z1.arloxcld.com".  This new name matches the SSL certificate too.

**Comment by twrecked** [comment]
It's exactly what the previous posts said. Sometime recently Arlo renamed their mqtt cluster. I don't have any devices using mqtt so it gets hard for me to track these changes.

Another thing to try might be 

```yaml
aarlo:
  ..your current config
  backend: sse
```

**Comment by alceasan** [comment]
I'm having exactly the same problem, after migrating to 0.8 version I'm not able to have it working.

I removed yaml config and setup everything in the UI, but I don't see the option here to set backend to 'sse':

<img width="391" alt="imagen" src="https://github.com/twrecked/hass-aarlo/assets/3265883/246e8737-c27d-49dd-a8e8-cfcbeaff7583">

**Comment by twrecked** [comment]
When you upgraded the code would have created a file called `aarlo.yaml`, this is where some of the config ended up. Add it into there.

```yaml
version: 1
aarlo:
  backend: sse
```
