### ISSUE TITLE
Failed to initialise Aarlo with v0.8.1a10

### ISSUE THREAD

**Issue by Nortifer** [twrecked/hass-aarlo#853]
After setting up the integration with the GUI I've got this error on the HA notifications : 

```
aarlo Component Setup
Error: general-error=gaierror
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/pyaarlo/backend.py", line 526, in _mqtt_main
self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 827, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name does not resolve

If error persists you might need to change config and restart.
```

I tried to add this on my configuration.yaml : 
```
aarlo:
  host: https://my.arlo.com
  username: !secret arlo_username
  password: !secret arlo_password
  mqtt_host: mqtt-cluster-z1.arloxcld.com
```
But it doesn't change anything

**Comment by cowboy-cod3r** [comment]
This is occurring because the default is set to an unresolvable host in the `pyaarlo` module [here](https://github.com/twrecked/pyaarlo/blob/master/pyaarlo/constant.py#L5).

With version 0.8, Im not sure where to provide the override configs but I was able to get this to work by updating the `custom_components/aarlo/cfg.py` file [here](https://github.com/twrecked/hass-aarlo/blob/7817e6f49c4f5c59c211abb513aa6aea5e2c5eb8/custom_components/aarlo/cfg.py#L496C12-L496C40) with the following:

```
options["mqtt_host"] = "mqtt-cluster-z1.arloxcld.com"

**Comment by Nortifer** [comment]
Thats work !
Thanks for the help

**Comment by acosta216** [comment]
I was having this issue yesterday and this fix resolved it for me also. Appreciate you posting!

**Comment by gchermette** [comment]
Did the trick too, thanks!!!

**Comment by Nortifer** [comment]
Quick update on it, seem's unrelated, but the camera is well detected on the initialization, but become unavailable shortly after. Does someone as the same problem ?

**Comment by glenp68** [comment]
Can someone direct me to where in the cfg.py file I need to add the option line?

Thanks all,

Glen.

**Comment by gchermette** [comment]
Hi

I inserted this in line 496, as displayed when you click on the link that cowboy-cod3r inserted.

Cheers

**Comment by bennyb0i** [comment]
> This is occurring because the default is set to an unresolvable host in the `pyaarlo` module [here](https://github.com/twrecked/pyaarlo/blob/master/pyaarlo/constant.py#L5).
> 
> With version 0.8, Im not sure where to provide the override configs but I was able to get this to work by updating the `custom_components/aarlo/cfg.py` file [here](https://github.com/twrecked/hass-aarlo/blob/7817e6f49c4f5c59c211abb513aa6aea5e2c5eb8/custom_components/aarlo/cfg.py#L496C12-L496C40) with the following:
> 
> ```
> options["mqtt_host"] = "mqtt-cluster-z1.arloxcld.com"
> ```
> 
> Once updated, just restart Home Assistant. Hope this helps!

Since the pyaarlo module was decoupled from the integration, the config now (typically) resides at `/srv/homeassistant/lib/python3.11/site-packages/pyaarlo/constant.py`. I adjusted line 5 of that file to the below and it worked without having to adjust `cfg.py`.

```
MQTT_HOST = "mqtt-cluster-z1.arloxcld.com"
```

Not sure if the change will survive an upgrade to Home Assistant but will find out in a couple days with the next release 😅.

**Comment by gchermette** [comment]
Way nicer solution, imho. thanks a lot!

**Comment by tesheridan** [comment]
Hi I added  'mqtt_host: mqtt-cluster-z1.arloxcld.com' to the aarlo.yaml file as below and worked for me. Thanks for the tips.

aarlo:
 mqtt_host: mqtt-cluster-z1.arloxcld.com

**Comment by cowboy-cod3r** [comment]
@bennyb0i Yeah, you'll lose the change if the pyaarlo package is updated (unless the value is updated in the source code).  That's the reason I updated the file that I did. @tesheridan has best solution IMO since it's updating config and not code.  I'm sure I tried that though and it didn't work for me.

**Comment by NoahJaehnert** [comment]
> ```
> options["mqtt_host"] = "mqtt-cluster-z1.arloxcld.com"
> ```

I was receiving the same issue as @Nortifer. @cowboy-cod3r's fix noted above allowed my aarlo integration to start working again, whereas @tesheridan's unfortuantely did not want to work for some reason. 

Just wanted to add that tidbit. Sounds like @cowboy-cod3r also had similar findings.

**Comment by twrecked** [comment]
Sorry, been on vacation.

For 0.8 like @tesheridan says, add it to/create a file called `aarlo.yaml` file. Something like this, and the spacing is important.

```yaml
version: 1
aarlo:
  mqtt_host: mqtt-cluster-z1.arloxcld.com
```

Anything else will be reset when you upgrade or delete/restart your container.

**Comment by Ralcidonis** [comment]
I had the same issue and this solution worked for me as well.

**Comment by pinsdorf** [comment]
I want to confim that above settings worked for me as well.

```
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  mqtt_host: mqtt-cluster-z1.arloxcld.com
```
