### ISSUE TITLE
Component Setup error

### ISSUE THREAD

**Issue by MrMoore66** [twrecked/hass-aarlo#871]
Updated to 0.8. I get this error during start up? Any idea?

aarlo Component Setup
Error: general-error=gaierror
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/pyaarlo/backend.py", line 526, in _mqtt_main
self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 827, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name does not resolve

If error persists you might need to change config and restart.

**Comment by twrecked** [comment]
Try the `sse` backend.

Create or modify `aarlo.yaml`:

```yaml
version: 1
aarlo:
  backend: sse
```

**Comment by Victor0815** [comment]
It works. Thx

**Comment by Megachip** [comment]
> Try the `sse` backend.
> 
> Create or modify `aarlo.yaml`:
> 
> ```yaml
> version: 1
> aarlo:
>   backend: sse
> ```

How to do it after yaml is deprecated?
