### ISSUE TITLE
invalid config error after installing Arlo to home assistant.  Import error: cannot import name "unidecode"  shown in log

### ISSUE THREAD

**Issue by Wibo70** [twrecked/hass-aarlo#873]
Using HACS, i've installed the arlo integration. 
after putting the required code in confiuguration file and a restart i'm greeted with the following message:

##
Invalid config
The following integrations and platforms could not be set up:

[aarlo]
aarlo.sensor 
aarlo.media_player
aarlo.light 
aarlo.alarm_control_panel
aarlo.camera
aarlo.switch
Please check your config and [logs]
##

The log/ traceback is showing the following:

##
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1483, in async_process_component_config
    platform = p_integration.get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/aarlo/__init__.py", line 29, in <module>
    from .pyaarlo.constant import (
  File "/config/custom_components/aarlo/pyaarlo/__init__.py", line 11, in <module>
    from .base import ArloBase
  File "/config/custom_components/aarlo/pyaarlo/base.py", line 37, in <module>
    from .device import ArloDevice
  File "/config/custom_components/aarlo/pyaarlo/device.py", line 3, in <module>
    from unidecode import unidecode
ImportError: cannot import name 'unidecode' from 'unidecode' (/usr/local/lib/python3.11/site-packages/unidecode/__init__.py)
##

The last line seems to be where things go wrong: unidecode import. 
This is basically where I get stuck. not having a clue how to resolve that particular error. 

Is there anyone out there that might have an answer (or similar issue?)

**Comment by twrecked** [comment]
This is a new one!

Which version of Home Assistant and Aarlo is this?

**Comment by Wibo70** [comment]
I think 0.7.4.2 for Aarlo, merly based on the fact that is shown on the top of page clicking the tile in HACS.. 
For Home assistant that would be 2024.1.3

**Comment by Wibo70** [comment]
O.. I found this on Reddit:
https://www.reddit.com/r/homeassistant/comments/u8arax/help_with_arlo_integration_from_hacs/

But i'm completely clueless what the people are talking about regarding solutions. 

the log file shows the same error though.

**Comment by twrecked** [comment]
'unidecode' is marked as a dependency for the _Aarlo_ package so should be brought in automatically by _Home Assistant_ when you restart the container. If it wasn't everyone would be seeing this.

I'll upgrade my _Home Assistant_ here and try.

**Comment by Wibo70** [comment]
Some additional info: 
Found myself updating HA recently, then some HACS things including Aarlo. That gave the invalid config error. 
removed and reinstalled arlo. Not resolving the issue.

**Comment by twrecked** [comment]
If you are using a container can you try deleting and recreating it?

You have a log about installing unidecode at the top.

**Comment by Wibo70** [comment]
Not sure i have containers. Did a hassio install, not sure how that installs itself. 
will dive into that earliest sunday evening. Am away for the weekend. 
thanks for the very fast response!

**Comment by Wibo70** [comment]
This issue is resolved, not sure my activities had anything to do with that. But just in case someone finds him/her self in the same situation, here's what i did do:

As I didn't have to many HACS things running, I decided to just remove 'm all. and re-install. That didn't resolve the issue. 
Then decided to remove it all again, including HACS, this time removing the aarlo code from config.yaml as well. (#) 
Update to the latest HA version & HA core, restart, install HACS, restart, install Aarlo, restart, add code to config, restart. The last restart took a bit more time, not sure why. But this time no errors messages, and the camera popped up in the HA-dashboard.

**Comment by twrecked** [comment]
Good to hear. I think was an issue with _Home Assistant_, the _Aarlo_ piece can only tell _HA_ what to install it doesn't do it itself.

I think removing and then adding back _Aarlo_ was probably what fixed it.
