### ISSUE TITLE
aarlo Component Setup Error: authentication failed

### ISSUE THREAD

**Issue by DaveR2419** [twrecked/hass-aarlo#886]
This started again today, anyone else?

**Comment by twrecked** [comment]
Which version are you on?

**Comment by DaveR2419** [comment]
.8 I believe. I may have broken it. I did delete the hacs integration.

**Comment by DaveR2419** [comment]
I thought maybe the hacs was no longer needed with new integration.

**Comment by twrecked** [comment]
You still need to install it with HACS.

There is a behind the scenes changes where the _pyaarlo_ has been made standalone. But you shouldn't notice that.

**Comment by DaveR2419** [comment]
I just did a restore back from two days ago, before i had deleted the hacs entry. Getting same error.

**Comment by DaveR2419** [comment]
My login does work from the web portal.

**Comment by DaveR2419** [comment]
Not receiving authentication code to email, I did yesterday.

**Comment by gioxx** [comment]
Same problem here.
I have tested with stable version 7 and also with the latest unstable branch 8, in both cases I encounter a failed authentication error.

**Comment by hendrikwolf** [comment]
I have the same problem. 
It started today after reloading the integration. The last authentication code (tfa) for login was about 2 weeks ago. However, no new authentication code is requested. The authentication process probably fails beforehand.

Version: v0.8.1.a11
Config: aarlo:
                user_agent: linux
                last_format: '%d.%m.%y %H:%M'
                backend: sse
                reconnect_every: 90
                request_timeout: 120
                stream_timeout: 180
                refresh_devices_every: 3

[aarlo.log](https://github.com/twrecked/hass-aarlo/files/14230685/aarlo.log)

**Comment by twrecked** [comment]
Can those of you on 0.8 (the alpha release) try adding `send_source` to your `aarlo.yaml` file.

```yaml
version: 1
aarlo:
  ...your current config
  send_source: true
```

And I'll try my test machine here as well.

**Comment by hendrikwolf79** [comment]
@twrecked Ok. Now it works. 
Perfect. Thanks!

**Comment by hendrikwolf** [comment]
@twrecked Now it works fine. Thanks.

**Comment by DaveR2419** [comment]
That fixed it, thanks!

**Comment by gioxx** [comment]
I entered the suggested change in the aarlo.yaml file but I keep having problems:

```
Error: general-error=gaierror
Traceback (most recent call last):
File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.11/site-packages/pyaarlo/backend.py", line 526, in _mqtt_main
self._event_client.connect(self._arlo.cfg.mqtt_host, port=443, keepalive=60)
File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
return self.reconnect()
^^^^^^^^^^^^^^^^
File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
sock = self._create_socket_connection()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.pyenv/versions/3.11.4/lib/python3.11/socket.py", line 827, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.pyenv/versions/3.11.4/lib/python3.11/socket.py", line 962, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

If error persists you might need to change config and restart.
```

**Comment by twrecked** [comment]
@gioxx https://github.com/twrecked/hass-aarlo/issues/871

**Comment by gioxx** [comment]
> @gioxx #871

Perfect, solved 😄

**Comment by gchermette** [comment]
Hi

I tried and added send_source: true, to no avail.
It seems aarlo tries to authenticate via email/imap, while I set configuration.yaml to push:

| configuration.yaml |
|--------|
| aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  tfa_source: push
  tfa_type:  PUSH
  mode_api: auto | 

| home-assistant.log |
|--------|
| 2024-02-16 11:08:36.072 ERROR (SyncWorker_3) [pyaarlo] session start failed
2024-02-16 11:08:36.251 WARNING (SyncWorker_3) [pyaarlo] body-error=JSONDecodeError
2024-02-16 11:08:37.274 WARNING (SyncWorker_3) [pyaarlo] body-error=JSONDecodeError
2024-02-16 11:08:38.294 WARNING (SyncWorker_3) [pyaarlo] body-error=JSONDecodeError
2024-02-16 11:08:39.295 ERROR (SyncWorker_3) [pyaarlo] authentication failed
2024-02-16 11:08:40.373 ERROR (SyncWorker_3) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2024-02-16 11:08:40.373 ERROR (SyncWorker_3) [pyaarlo] 2fa startup failed
2024-02-16 11:08:40.380 ERROR (SyncWorker_3) [custom_components.aarlo] unable to connect to Arlo: attempt=4,sleep=120,error=2fa startup failed
2024-02-16 11:08:40.380 ERROR (SyncWorker_3) [custom_components.aarlo] unable to connect to Arlo: stopping retries, too may failures
 | 

Authentication was working fine until a day or 2 ago…
I updated aarlo to the latest version 2-3 days ago (I think this is 0.8.1, but cannot find anything in home-assistant that shows the version number)
What did I miss?

Thanks in advance

**Comment by gchermette** [comment]
Hi again,
I moved all configuration from configuration.yaml to aarlo.yaml, and while 2FA still fails as it still tries to use imap rather than iPhone, I have a different error message:
| home-assistant.log |
|--------|
| 2024-02-16 11:34:27.007 ERROR (SyncWorker_5) [pyaarlo] session start failed
2024-02-16 11:34:27.561 ERROR (SyncWorker_5) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2024-02-16 11:34:27.561 ERROR (SyncWorker_5) [pyaarlo] 2fa startup failed
2024-02-16 11:34:28.109 ERROR (SyncWorker_5) [pyaarlo] imap connection failed[Errno -2] Name does not resolve
2024-02-16 11:34:28.109 ERROR (SyncWorker_5) [pyaarlo] 2fa startup failed
2024-02-16 11:34:28.116 ERROR (SyncWorker_5) [custom_components.aarlo] unable to connect to Arlo: attempt=4,sleep=120,error=2fa startup failed
2024-02-16 11:34:28.116 ERROR (SyncWorker_5) [custom_components.aarlo] unable to connect to Arlo: stopping retries, too may failures |

**Comment by twrecked** [comment]
@gchermette The HACS tab will let you know the version number. You can't seem to get any version numbers from the integration page.

### If you're on 0.8:
You're still using push because that information is held in the Home Assistant configuration now so changing `configuration.yaml` won't change anything. Try looking in `.storage/core.config_entries` for the word `aarlo`. You could try changing the following settings:

```yaml
  "tfa_source": "push"
  "tfa_type": "push"
```

I can't find a way of changing the _Aarlo_ login setting from inside Home Assistant without deleting and re-installing it.

**Comment by gchermette** [comment]
Many thanks!!!
That worked! Lucky me that I remember how to edit files and find keywords in them via vi

I had to remove all variables I moved into aarlo.yaml file, or aarlo wouldn’t start, but that was simple enough to fix.

Many thanks again!

**Comment by twrecked** [comment]
Glad it's working again!

There has to be a easier way to change the login but I don't seem to be able to find it. None of the other integrations I use seem to have this feature as well. But I'll keep looking.

**Comment by thomasdupkavich94** [comment]
im having the same issue and i keep see everyone say aarlo.yaml file. but no where in any directory do i see an aarlo.yaml file. I did everything in the config flow popup when i click the integration. what exactly else so i need to add? do i need to create the aarlo.yaml file? and where exactly do i add it. None of these directions are clear. do i also need to have anything relevant to aarlo added in the config.yaml if im on 8.1a11
