### ISSUE TITLE
Issue when initiating AARLO with cameras linked to several base station

### ISSUE THREAD

**Issue by sylvain-prt** [twrecked/hass-aarlo#894]
Hello

First thanks a lot for this integration :-)

I've some issues with my setup and would like to see if there are solutions:

I have 2 base stations with cameras & ring bell devices.
If the HA arlo user has access to cameras from the 2 base stations, AARLO is failing to initialise and generate some errors

If I only assign cameras from 1 station to my HA arlo user, everything is working fine.

2024-02-29 00:22:33.456 DEBUG (SyncWorker_5) [custom_components.aarlo] login succeeded, attempt=1
2024-02-29 00:22:33.457 DEBUG (ArloBackgroundWorker) [pyaarlo] loading image library (30 days)
2024-02-29 00:22:33.459 INFO (MainThread) [homeassistant.setup] Setup of domain aarlo took 5.6 seconds
2024-02-29 00:22:33.464 INFO (MainThread) [homeassistant.components.camera] Setting up camera.aarlo
2024-02-29 00:22:33.465 INFO (MainThread) [custom_components.aarlo.camera] ArloCam: Garage created
2024-02-29 00:22:33.465 INFO (MainThread) [custom_components.aarlo.camera] ArloCam: Extérieur created
2024-02-29 00:22:33.465 INFO (MainThread) [custom_components.aarlo.camera] ArloCam: Entrée created
2024-02-29 00:22:33.465 INFO (MainThread) [custom_components.aarlo.camera] ArloCam: Jardin created
2024-02-29 00:22:33.465 INFO (MainThread) [custom_components.aarlo.camera] ArloCam: Salon created
2024-02-29 00:22:33.465 INFO (MainThread) [custom_components.aarlo.camera] installing handlers
2024-02-29 00:22:33.467 ERROR (MainThread) [pyaarlo] Could not find any base stations for device Garage
2024-02-29 00:22:33.467 ERROR (MainThread) [pyaarlo] Could not find any base stations for device Garage
2024-02-29 00:22:33.468 ERROR (MainThread) [pyaarlo] Could not find any base stations for device Extérieur
2024-02-29 00:22:33.469 ERROR (MainThread) [pyaarlo] Could not find any base stations for device Extérieur
2024-02-29 00:22:33.469 ERROR (MainThread) [pyaarlo] Could not find any base stations for device Entrée
2024-02-29 00:22:33.470 ERROR (MainThread) [pyaarlo] Could not find any base stations for device Entrée
2024-02-29 00:22:33.470 ERROR (MainThread) [pyaarlo] Could not find any base stations for device Jardin
2024-02-29 00:22:33.470 ERROR (MainThread) [pyaarlo] Could not find any base stations for device Jardin
2024-02-29 00:22:33.471 ERROR (MainThread) [pyaarlo] Could not find any base stations for device Salon
2024-02-29 00:22:33.471 ERROR (MainThread) [pyaarlo] Could not find any base stations for device Salon
2024-02-29 00:22:33.472 ERROR (MainThread) [homeassistant.components.camera] Error adding entities for domain camera with platform aarlo
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
await asyncio.gather(*tasks)
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 754, in _async_add_entity
await entity.add_to_platform_finish()
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 1025, in add_to_platform_finish
self.async_write_ha_state()
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
self._async_write_ha_state()
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 789, in _async_generate_attributes
attr.update(self.extra_state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/aarlo/camera.py", line 536, in extra_state_attributes
(ATTR_TIME_ZONE, self._camera.timezone),
^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/aarlo/pyaarlo/device.py", line 325, in timezone
return self.base_station.timezone
^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'timezone'
2024-02-29 00:22:33.484 ERROR (MainThread) [homeassistant.components.camera] Error while setting up aarlo platform for camera
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 369, in _async_setup_platform
await asyncio.gather(*pending)
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
await asyncio.gather(*tasks)
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 754, in _async_add_entity
await entity.add_to_platform_finish()
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 1025, in add_to_platform_finish
self.async_write_ha_state()
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
self._async_write_ha_state()
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 789, in _async_generate_attributes
attr.update(self.extra_state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/aarlo/camera.py", line 536, in extra_state_attributes
(ATTR_TIME_ZONE, self._camera.timezone),
^^^^^^^^^^^^^^^^^^^^^
File "/home/homeassistant/.homeassistant/custom_components/aarlo/pyaarlo/device.py", line 325, in timezone
return self.base_station.timezone

![image](https://github.com/twrecked/hass-aarlo/assets/53967022/7eb529c6-b796-4088-9a15-d406fd20f0f5)

If you have any idea on how to solve me issue :)

Thanks a lot
Sylvain
@sylvain-prt

**Comment by twrecked** [comment]
We should support this, I have 2 base stations for my cameras and it works fine.

Some things to try:

- What kind of cameras are these?
- Do you give the HA Arlo account admin access?
- Can you log into the Arlo web page with your Home Assistant Arlo account and see what it looks like?

**Comment by sylvain-prt** [comment]
I just re-added the 2nd base camera and after restarting HA, they are now showing up !!!

is it possible that the initial setup requires to be limited to only 1 base ?

I'm sorry for the false alarm !!!

**Comment by twrecked** [comment]
From the component side it makes no difference if there is 1 or more bases and if it's the first time or later ones.

Who knows at the Arlo level. And it's been a long time since I had to share devices with a user. Maybe using their website helpd.

Glad it's working now!

**Comment by sylvain-prt** [comment]
thanks a lot !
