### ISSUE TITLE
RuntimeError: no running event loop

### ISSUE THREAD

**Issue by jezzamine** [twrecked/hass-aarlo#907]
Updated to 2024.4.0 and log is filling with errors then HA restarts. Rolling back to 2024.3.3 doesn't produce these errors.

**Comment by twrecked** [comment]
Do you have any automations using Arlo devices?

**Comment by collse** [comment]
I also have the entire integration disabled as it is crashing my Hass.

I also have automations enabled here is one for you

> alias: Camera - Arlo Control Panel
description: ""
trigger:
  - platform: state
    entity_id:
      - person.A
    for:
      hours: 0
      minutes: 5
      seconds: 0
    to: not_home
  - platform: state
    entity_id:
      - person.B
    for:
      hours: 0
      minutes: 5
      seconds: 0
    to: not_home
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'not_home' }}"
              - condition: and
                conditions:
                  - condition: state
                    entity_id: person.A
                    state: not_home
                    for:
                      hours: 0
                      minutes: 0
                      seconds: 0
                  - condition: state
                    entity_id: person.B
                    state: not_home
                    for:
                      hours: 0
                      minutes: 0
                      seconds: 0
        sequence:
          - service: alarm_control_panel.alarm_arm_away
            data: {}
            target:
              entity_id:
                - alarm_control_panel.aarlo_base
                - alarm_control_panel.aarlo_nursery
    default:
      - service: alarm_control_panel.alarm_arm_home
        data: {}
        target:
          entity_id:
            - alarm_control_panel.aarlo_base
            - alarm_control_panel.aarlo_nursery
mode: restart


here is another:

> alias: Camera - Arlo - Enable On HA Start
description: ""
trigger:
  - event: start
    platform: homeassistant
condition: []
action:
  - service: camera.enable_motion_detection
    data: {}
    target:
      entity_id:
        - camera.aarlo_hallway
        - camera.aarlo_kitchen
        - camera.aarlo_spare
        - camera.aarlo_landing
        - camera.aarlo_nursery
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: alarm_control_panel.alarm_arm_home
    data: {}
    target:
      entity_id:
        - alarm_control_panel.aarlo_base
        - alarm_control_panel.aarlo_nursery
mode: single

and another:

> alias: Camera - Arlo - Camera Snapshot
description: ""
trigger:
  - entity_id:
      - camera.aarlo_spare
      - camera.aarlo_kitchen
      - camera.aarlo_hallway
      - camera.aarlo_landing
    for:
      hours: 0
      minutes: 0
      seconds: 3
    from: idle
    platform: state
    to: recording
  - entity_id:
      - camera.aarlo_hallway
      - camera.aarlo_landing
      - camera.aarlo_spare
      - camera.aarlo_kitchen
    for:
      hours: 0
      minutes: 0
      seconds: 3
    from: recently active
    platform: state
    to: recording
condition: []
action:
  - data_template:
      entity_id: "{{ trigger.entity_id }}"
    service: aarlo.camera_request_snapshot
mode: single


there are others, where I eg look for all cameras for motion and in case it is true while all people are away I would issue a notification via notify.

**Comment by collse** [comment]
additional logs I get after enabling PROFILER.SET_ASYNCIO_DEBUG

```
2024-04-06 12:07:16.355 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=RuntimeError
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/background.py", line 35, in _run_next
    job["callback"](**job["args"])
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 256, in _clear_recent
    self._do_callbacks(RECENT_ACTIVITY_KEY, False)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/super.py", line 70, in _do_callbacks
    cb(self, attr, value)
  File "/config/custom_components/aarlo/camera.py", line 410, in update_state
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1233, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1181, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2181, in async_set
    self._bus._async_fire(  # pylint: disable=protected-access
  File "/usr/src/homeassistant/homeassistant/core.py", line 1459, in _async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 686, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args), name=hassjob.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 457, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 832, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one

2024-04-06 12:07:16.355 ERROR (ArloBackgroundWorker) [homeassistant] Error doing job: Task was destroyed but it is pending!:   File "/usr/local/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/background.py", line 67, in run
    timeout = self._run_next()
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/background.py", line 35, in _run_next
    job["callback"](**job["args"])
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 256, in _clear_recent
    self._do_callbacks(RECENT_ACTIVITY_KEY, False)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/super.py", line 70, in _do_callbacks
    cb(self, attr, value)
  File "/config/custom_components/aarlo/camera.py", line 410, in update_state
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1233, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1181, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2181, in async_set
    self._bus._async_fire(  # pylint: disable=protected-access
  File "/usr/src/homeassistant/homeassistant/core.py", line 1459, in _async_fire
    self._hass.async_add_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 686, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args), name=hassjob.name)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 457, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)

```

**Comment by bdraco** [comment]
https://github.com/twrecked/hass-aarlo/blob/c56230381f7c0a413c54430a47ad73aff9f86e38/custom_components/aarlo/camera.py#L410

Change that from `self.async_schedule_update_ha_state()` to `self.schedule_update_ha_state()`

Its not running in the main thread

https://github.com/twrecked/hass-aarlo/blob/c56230381f7c0a413c54430a47ad73aff9f86e38/custom_components/aarlo/camera.py#L340

remove `@callback` as that code is not being called from the event loop

**Comment by bdraco** [comment]
This problem looks like its present in almost all the platforms.  Using the async api in another thread is not thread safe, and any time that code is called it can crash HA.

https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading

**Comment by collse** [comment]
> This problem looks like its present in almost all the platforms. Using the async api in another thread is not thread safe, and any time that code is called it can crash HA.
> 
> https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading

Sounds like a wider issue then that more people may need to address?

**Comment by twrecked** [comment]
Thanks all. I took a quick look on Friday and came to the same conclusions you did.

And now I finally got some time proper to look at this. The first thing to do is reproduce it, so thanks for the automations. And then I'll try and fix it, I should be able to shove a job onto the main loop.

(Although I feel like the HA API should be handing this better. And the docs are a bit woeful on this stuff.)

And according to this, tschamm/boschshc-hass#176, maybe drop back a revision for now.

**Comment by twrecked** [comment]
Are people using 0.8? I can't reproduce the crash here.

**Comment by collse** [comment]
I was using 0.81b13 and just saw there is a b14 which I will give a go

**Comment by collse** [comment]
Looking good so far 👍🏽🙏🏽
