### ISSUE TITLE
Config setup won't complete.

### ISSUE THREAD

**Issue by robkgriffiths** [twrecked/hass-aarlo#915]
Hi,

Since trying the latest version I am unable to complete the setup.  I have cleared all the yaml configs and just added the following to the aarlo.yaml file.

version: 1
aarlo:
backend: sse
mqtt_host: mqtt-cluster-z1.arloxcld.com

I have also gone through all the config setup via the integration using a dedicated HA Arlo account.  Also using 2FA via IMAP using a gmail app password.  No matter what I try, I keep getting the error below.  I think it is authenticating ok as I changed the password to an incorrect one as a test and I then started getting authentication errors.  On the integration itself it has an error "Failed to set up" and the message no devices or entities.

Any idea guys?

Logger: homeassistant.config_entries
Source: config_entries.py:551
First occurred: 14:02:55 (1 occurrences)
Last logged: 14:02:55

Error setting up entry Aarlo for **************@gmail.com for aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aarlo/__init__.py", line 240, in async_setup_entry
    cfg = BlendedCfg(hass, entry.data, entry.options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aarlo/cfg.py", line 332, in __init__
    self._load()
  File "/config/custom_components/aarlo/cfg.py", line 348, in _load
    self._main_config.update(config.get(COMPONENT_DOMAIN, {}))
TypeError: 'NoneType' object is not iterable

**Comment by twrecked** [comment]
When you say latest version - what number exactly? And can you show the contents of the `aarlo.yaml` properly formatted? ie, using the 3 backticks around it.

**Comment by robkgriffiths** [comment]
I went back and double checked the version.   I believed I was using the latest but it was in fact version 0.7.  I have since manually installed it and Aarlo is now working for me.   
Thanks again.
