### ISSUE TITLE
Several new warnings starting with HA 2024.5.0b1 for using non-threadsafe APIs

### ISSUE THREAD

**Issue by rccoleman** [twrecked/hass-aarlo#919]
HA 2024.5.0b0 introduced some new checks for integrations that call non-threadsafe APIs and there are several instances in aarlo.

bdraco suggested the following in Discord:
> Fix is probably to switch it to self.schedule_update_ha_state(). (drop the async_).

```
2024-04-24 19:24:51.721 WARNING (ArloBackgroundWorker) [homeassistant.helpers.frame] Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(), please report it to the author of the 'aarlo' custom integration
2024-04-24 19:24:51.724 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=RuntimeError
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/background.py", line 35, in _run_next
    job["callback"](**job["args"])
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 480, in _event_handler
    self._set_recent(self._arlo.cfg.recent_time)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 249, in _set_recent
    self._do_callbacks(RECENT_ACTIVITY_KEY, True)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/super.py", line 70, in _do_callbacks
    cb(self, attr, value)
  File "/config/custom_components/aarlo/camera.py", line 408, in update_state
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1258, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(). Please report it to the author of the 'aarlo' custom integration.
2024-04-24 19:24:51.730 WARNING (ArloBackgroundWorker) [homeassistant.helpers.frame] Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(), please report it to the author of the 'aarlo' custom integration
2024-04-24 19:24:51.735 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=RuntimeError
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/background.py", line 35, in _run_next
    job["callback"](**job["args"])
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 480, in _event_handler
    self._set_recent(self._arlo.cfg.recent_time)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 249, in _set_recent
    self._do_callbacks(RECENT_ACTIVITY_KEY, True)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/super.py", line 70, in _do_callbacks
    cb(self, attr, value)
  File "/config/custom_components/aarlo/camera.py", line 408, in update_state
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1258, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(). Please report it to the author of the 'aarlo' custom integration.
2024-04-24 19:24:51.741 WARNING (ArloBackgroundWorker) [homeassistant.helpers.frame] Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(), please report it to the author of the 'aarlo' custom integration
2024-04-24 19:24:51.744 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=RuntimeError
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/background.py", line 35, in _run_next
    job["callback"](**job["args"])
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 480, in _event_handler
    self._set_recent(self._arlo.cfg.recent_time)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 249, in _set_recent
    self._do_callbacks(RECENT_ACTIVITY_KEY, True)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/super.py", line 70, in _do_callbacks
    cb(self, attr, value)
  File "/config/custom_components/aarlo/camera.py", line 408, in update_state
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1258, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(). Please report it to the author of the 'aarlo' custom integration.
2024-04-24 19:27:47.231 INFO (MainThread) [homeassistant.components.automation.door_close] Door Close: Running automation actions
2024-04-24 19:27:47.232 INFO (MainThread) [homeassistant.components.automation.door_close] Door Close: Executing step call service
2024-04-24 19:34:51.025 WARNING (ArloBackgroundWorker) [homeassistant.helpers.frame] Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(), please report it to the author of the 'aarlo' custom integration
2024-04-24 19:34:51.027 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=RuntimeError
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/background.py", line 35, in _run_next
    job["callback"](**job["args"])
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 480, in _event_handler
    self._set_recent(self._arlo.cfg.recent_time)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 249, in _set_recent
    self._do_callbacks(RECENT_ACTIVITY_KEY, True)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/super.py", line 70, in _do_callbacks
    cb(self, attr, value)
  File "/config/custom_components/aarlo/camera.py", line 408, in update_state
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1258, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(). Please report it to the author of the 'aarlo' custom integration.
2024-04-24 19:34:51.031 WARNING (ArloBackgroundWorker) [homeassistant.helpers.frame] Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(), please report it to the author of the 'aarlo' custom integration
2024-04-24 19:34:51.033 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=RuntimeError
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/background.py", line 35, in _run_next
    job["callback"](**job["args"])
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 480, in _event_handler
    self._set_recent(self._arlo.cfg.recent_time)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 249, in _set_recent
    self._do_callbacks(RECENT_ACTIVITY_KEY, True)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/super.py", line 70, in _do_callbacks
    cb(self, attr, value)
  File "/config/custom_components/aarlo/camera.py", line 408, in update_state
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1258, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(). Please report it to the author of the 'aarlo' custom integration.
2024-04-24 19:34:51.038 WARNING (ArloBackgroundWorker) [homeassistant.helpers.frame] Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(), please report it to the author of the 'aarlo' custom integration
2024-04-24 19:34:51.039 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=RuntimeError
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/background.py", line 35, in _run_next
    job["callback"](**job["args"])
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 480, in _event_handler
    self._set_recent(self._arlo.cfg.recent_time)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/camera.py", line 249, in _set_recent
    self._do_callbacks(RECENT_ACTIVITY_KEY, True)
  File "/usr/local/lib/python3.12/site-packages/pyaarlo/super.py", line 70, in _do_callbacks
    cb(self, attr, value)
  File "/config/custom_components/aarlo/camera.py", line 408, in update_state
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1258, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(). Please report it to the author of the 'aarlo' custom integration.
2024-04-24 19:40:43.533 INFO (MainThread) [alexapy.alexaapi] Backing off _static_request(...) for 1.0s (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/camera.py, line 408: self.async_schedule_update_ha_state(). Please report it to the author of the 'aarlo' custom integration.
```

**Comment by twrecked** [comment]
Which version are you on?

**Comment by rccoleman** [comment]
I noticed that there was an update that HACS didn't show ([v0.8.1.b15](https://github.com/twrecked/hass-aarlo/tree/v0.8.1.b15)) and I don't see the messages with it.  Looks good now, thanks!
