### ISSUE TITLE
Traceback Error thrown from custom component. 

### ISSUE THREAD

**Issue by gangemij** [twrecked/hass-aarlo#928]
After updating to lates HA code. Traceback thrown in GUI. 

['job-error=RuntimeError\nTraceback (most recent call last):\n File "/config/custom_components/aarlo/pyaarlo/background.py", line 35, in _run_next\n job["callback"](https://github.com/twrecked/hass-aarlo/issues/new)\n File "/config/custom_components/aarlo/pyaarlo/base.py", line 529, in _ping_and_check_reply\n self._save_and_do_callbacks(CONNECTION_KEY, "available")\n File "/config/custom_components/aarlo/pyaarlo/super.py", line 77, in _save_and_do_callbacks\n self._do_callbacks(attr, value)\n File "/config/custom_components/aarlo/pyaarlo/super.py", line 70, in _do_callbacks\n cb(self, attr, value)\n File "/config/custom_components/aarlo/binary_sensor.py", line 116, in update_state\n self.async_schedule_update_ha_state()\n File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1258, in async_schedule_update_ha_state\n self.async_write_ha_state()\n File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state\n self.hass.verify_event_loop_thread("async_write_ha_state")\n File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread\n frame.report(\n File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report\n _report_integration(what, integration_frame, level, error_if_integration)\n File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration\n raise RuntimeError(\nRuntimeError: Detected that custom integration 'aarlo' calls async_write_ha_state from a thread at custom_components/aarlo/binary_sensor.py, line 116: self.async_schedule_update_ha_state(). Please report it to the author of the 'aarlo' custom integration.\n']

**Comment by twrecked** [comment]
It should be fixed in both 0.7 and 0.8
