### ISSUE TITLE
Forbidden for url: https://my.arlo.com/hmsweb/client/subscribe

### ISSUE THREAD

**Issue by mikesalz** [twrecked/hass-aarlo#946]
I have been getting this error all day.  Thoughts?

2024-05-17 21:20:16.289 ERROR (ArloEventStream) [pyaarlo] general-error=HTTPError
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/pyaarlo/backend.py", line 593, in _sse_main
self._event_client = SSEClient(
^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 55, in __init__
self._connect()
File "/usr/local/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 74, in _connect
self.resp.raise_for_status()
File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://my.arlo.com/hmsweb/client/subscribe

**Comment by twrecked** [comment]
This is a new one. 

You don't say what version you are using so I'm going to assume 0.8. Look inside `aarlo.yaml`  and remove the `backend` setting if it's set. I think _Arlo_ wants you to use `mqtt`.

**Comment by mikesalz** [comment]
I apologize - I submitted this issue quickly without much detail.  But I appreciate your help!  I am on version 0.8.1.2.  And I did have `backend` in my aarlo.yaml.  I removed that, and it seems to be behaving better now.  Thank you!

**Comment by Arnoudd** [comment]
Same issue here. And the removal of the backend config fixed my problem too. Thanks!
