### ISSUE TITLE
OSError: [Errno 24] No file descriptors available

### ISSUE THREAD

**Issue by AnonymousRetard** [twrecked/hass-aarlo#949]
Two or three times so far (in the last 2-3 days) my Home assistant instance has been crashing because it's running out of file descriptors.
I ran `lsof -p` on the hass instance and there's a lot of connections stuck in the "CLOSE_WAIT" state to the ip-addresses 104.18.40.18 & 172.64.147.238.

Today I restarted homeassistant again and looking at the logs after just ~15 minutes of uptime there's 36 occurances of the error below:

```
general-error=HTTPError Traceback (most recent call last): File "/etc/homeassistant/deps/lib/python3.12/site-packages/urllib3/response.py", line 444, in _error_catcher yield File "/etc/homeassistant/deps/lib/python3.12/site-packages/urllib3/response.py", line 828, in read_chunked self._update_chunk_length() File "/etc/homeassistant/deps/lib/python3.12/site-packages/urllib3/response.py", line 758, in _update_chunk_length line = self._fp.fp.readline() ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/socket.py", line 707, in readinto return self._sock.recv_into(b) ^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/ssl.py", line 1252, in recv_into return self.read(nbytes, buffer) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/ssl.py", line 1104, in read return self._sslobj.read(len, buffer) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TimeoutError: The read operation timed out During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/lib/python3.12/site-packages/requests/models.py", line 816, in generate yield from self.raw.stream(chunk_size, decode_content=True) File "/etc/homeassistant/deps/lib/python3.12/site-packages/urllib3/response.py", line 624, in stream for line in self.read_chunked(amt, decode_content=decode_content): File "/etc/homeassistant/deps/lib/python3.12/site-packages/urllib3/response.py", line 816, in read_chunked with self._error_catcher(): File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__ self.gen.throw(value) File "/etc/homeassistant/deps/lib/python3.12/site-packages/urllib3/response.py", line 449, in _error_catcher raise ReadTimeoutError(self._pool, None, "Read timed out.") urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='my.arlo.com', port=443): Read timed out. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/etc/homeassistant/deps/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 86, in __next__ next_chunk = next(self.resp_iterator) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/site-packages/requests/models.py", line 822, in generate raise ConnectionError(e) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='my.arlo.com', port=443): Read timed out. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/etc/homeassistant/deps/lib/python3.12/site-packages/pyaarlo/backend.py", line 601, in _sse_main for event in self._event_client: File "/etc/homeassistant/deps/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 103, in __next__ self._connect() File "/etc/homeassistant/deps/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 74, in _connect self.resp.raise_for_status() File "/usr/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://my.arlo.com/hmsweb/client/subscribe
general-error=HTTPError Traceback (most recent call last): File "/etc/homeassistant/deps/lib/python3.12/site-packages/pyaarlo/backend.py", line 593, in _sse_main self._event_client = SSEClient( ^^^^^^^^^^ File "/etc/homeassistant/deps/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 55, in __init__ self._connect() File "/etc/homeassistant/deps/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 74, in _connect self.resp.raise_for_status() File "/usr/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://my.arlo.com/hmsweb/client/subscribe
```

If I ping my.arlo.com it resolves to 104.18.40.18 so I think it's the aarlo integration causing the issue... I also noticed now that all my Aarlo sensors are unavailable.

I tried deleting aarlo.pickle & session.pickle in the .aarlo folder and the reloading the integration but the problem remains. This error also showed up in the log now:

```
Logger: pyaarlo
Source: deps/lib/python3.12/site-packages/pyaarlo/__init__.py:742
First occurred: 23:02:02 (8 occurrences)
Last logged: 23:03:44

body-error=KeyError
error in new response={'meta': {'code': 400, 'error': 9204, 'message': 'Browser is not trusted'}}
```

**Comment by twrecked** [comment]
Try removing the `backend` option from `/config/aarlo.yaml`.

**Comment by AnonymousRetard** [comment]
This seems to have fixed it, thanks!
