### ISSUE TITLE
Issue after HA restart

### ISSUE THREAD

**Issue by petepall** [twrecked/hass-aarlo#951]
Hello,

After my HA restart of today I’m getting the following error:

Aarlo component setup:
Error: general-error=HTTPError
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/pyaarlo/backend.py", line 593, in _sse_main
self._event_client = SSEClient(
^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 55, in init
self._connect()
File "/usr/local/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 74, in _connect
self.resp.raise_for_status()
File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://my.arlo.com/hmsweb/client/subscribe

If error persists you might need to change config and restart.

Any idea what could be causing this error?
Version installed: 0.8.1.2

**Comment by twrecked** [comment]
Duplicate of #946

**Comment by petepall** [comment]
Hi @twrecked, I removed the backend setting but still get the same error message.

**Comment by petepall** [comment]
After doing another restart as some items did not load correctly I now get the error but after about 3 to 4 minutes that app loads and the Aarlo integration works.
