### ISSUE TITLE
Aarlo in HomeAssistant notification (It's not working anymore)

### ISSUE THREAD

**Issue by JDR1972** [twrecked/hass-aarlo#956]
This is the notification I get:

aarlo Component Setup
Error: general-error=HTTPError
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/pyaarlo/backend.py", line 593, in _sse_main
self._event_client = SSEClient(
^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 55, in init
self._connect()
File "/usr/local/lib/python3.12/site-packages/pyaarlo/sseclient.py", line 74, in _connect
self.resp.raise_for_status()
File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://my.arlo.com/hmsweb/client/subscribe

If error persists you might need to change config and restart.

------------------------------------------------------------------- 

In my settings, I have 7 repairs all about unused YAML configuration for the aarlo integration.

=

**Comment by twrecked** [comment]
Duplicate of #946 

And you see the repair notification because you upgraded to 0.8 from 0.7 and it uses the proper _Home Assistant_ integration mechanism. You can leave them for now or comment them out if you want.

**Comment by JDR1972** [comment]
Thank you.  I didn't even realize it had been updated.
