### ISSUE TITLE
Aarlo video not working anymore

### ISSUE THREAD

**Issue by wierts** [twrecked/hass-aarlo#977]
recently i got my arlo integration to work again, exept for the video feed. 

All atributes are shown, the camera's the battery percentage etc. 
hoewever when trying to access the camera / video feature the following message appears

_This entity is no longer being provided by the aarlo integration. If the entity is no longer in use, delete it in settings._

![image](https://github.com/user-attachments/assets/64b7fc89-6716-437d-9c01-d238169c4549)
see the status of (one of my cameras). I have a total of 5 cameras connected. all 5 are shown in HA. however none of the video work.

my infomation

Home Assistant

Core
2024.7.4
Supervisor
2024.08.0
Operating System
12.4
Frontend
20240710.0

below the details of my arlo integration
![image](https://github.com/user-attachments/assets/e1a808cc-5e7b-40d0-84e3-66d9d57e7409)

**Comment by aeg1990** [comment]
I too have this issue.

**Comment by Dan1jel** [comment]
Also got this issue, all works except the picture in Lovelace(!?)

```
Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:608
integration: Camera (documentation, issues)
First occurred: 08:18:25 (2 occurrences)
Last logged: 08:18:26

Error adding entity camera.aarlo_camera_1 for domain camera with platform aarlo
Error adding entity camera.aarlo_camera_2 for domain camera with platform aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 208, in report_usage
    integration_frame = get_integration_frame(
        exclude_integrations=exclude_integrations
    )
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 113, in get_integration_frame
    raise MissingIntegrationFrame
homeassistant.helpers.frame.MissingIntegrationFrame

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1384, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 944, in async_write_ha_state
    super().async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1087, in __async_calculate_state
    if state_attributes := self.state_attributes:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 812, in state_attributes
    if frontend_stream_type := self.frontend_stream_type:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 586, in frontend_stream_type
    report_usage(
    ~~~~~~~~~~~~^
        (
        ^
    ...<4 lines>...
        exclude_integrations={DOMAIN},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 227, in report_usage
    raise RuntimeError(msg) from err
RuntimeError: Detected code that is setting the '_attr_frontend_stream_type' attribute in the ArloCam class, which is deprecated and will be removed in Home Assistant 2025.6, . Please report this issue
```

**Comment by wierts** [comment]
is there any additional information we can provide to aid in the receovery of the video stream? tnx
