### ISSUE TITLE
Arlo All-In One Sensors Not Working

### ISSUE THREAD

**Issue by ParP924** [twrecked/hass-aarlo#991]
I was successfully able to add the Aarlo integration on my HA instance and I am able to view my camera streams however, I am not able to see any updates on HA when opening and closing doors.

Also another (possible) issue is that I cannot Arm/Disarm my system through the Arlo Keypad HA entity however I can do it through an Aarlo For xxxx@gmail.com "Unknown" entity. 
<img src="https://github.com/user-attachments/assets/4caf77f9-31c4-442c-aac2-1333d4ef5e2a" width=50% height=50%>

**Comment by twrecked** [comment]
As far as I'm aware the all-in-1 sensors work.

Can you turn on an attach some debug. Start with the time you are opening and closing doors.

**Comment by ParP924** [comment]
> As far as I'm aware the all-in-1 sensors work.
> 
> 
> 
> Can you turn on an attach some debug. Start with the time you are opening and closing doors.
> 
> 

I am not sure where I can find the logs but I have turned on debugging options within HA. I checked the documentation on how to enable debug but I cannot seem to find /config/aarlo.yaml file.

**Comment by ParP924** [comment]
Could you also let me know if there is an older version of the integration where the all in one sensors work?

**Comment by twrecked** [comment]
You have to create `/config/aarlo.yaml` if it's not there.

I assumed all the old versions were working with it. Nobody else has said anything, you could try on the home assistant community website, there are some pretty good people on there.

I think I might have a fix for the 'browser not trusted' issue; I'll check it here first.

**Comment by ParP924** [comment]
Could you share the minimum content that needs to be in aarlo.yml file?

**Comment by twrecked** [comment]
https://github.com/twrecked/hass-aarlo#enabling-debug

```
aarlo:
  verbose_debug: true
```

**Comment by ParP924** [comment]
Looks like even after adding the verbose logger it still just gives me the same log. 

```
This error originated from a custom integration.

Logger: pyaarlo
Source: custom_components/aarlo/__init__.py:408
integration: Arlo Camera Support (documentation, issues)
First occurred: 10:21:32 PM (5 occurrences)
Last logged: 10:21:35 PM

session start failed
body-error=KeyError
error in new response={'meta': {'code': 400, 'error': 9204, 'message': 'Browser is not trusted'}}
```

**Comment by twrecked** [comment]
It should all be in `/config/home-assistant.log`.

**Comment by ParP924** [comment]
Hey there, Have been busy for a while but the issue with sensors not working is still present. My current version of aarlo is: `0.8.1.8`

```py
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
First occurred: 7:56:43 AM (6 occurrences)
Last logged: 7:56:44 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x02'
      ^
```

**Comment by ParP924** [comment]
Also noticed that everytime I get a key error it is thrown by a SyncWorker (if that helps)
```
![image](https://github.com/user-attachments/assets/0dadfc14-da32-4cdb-8199-2d2aeb785a1e)

```
