### ISSUE TITLE
Error on setting up Aarlo please help. solved

### ISSUE THREAD

**Issue by platini76** [twrecked/hass-aarlo#994]
Registratore: homeassistant.config_entries
Fonte: /usr/src/homeassistant/homeassistant/config_entries.py:688
Prima occorrenza: 19:14:08 (1 occorrenze)
Ultima registrazione: 19:14:08

Error setting up entry Aarlo for info@ooo.oot for aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aarlo/__init__.py", line 241, in async_setup_entry
    await cfg.async_load_and_merge(entry.data, entry.options)
  File "/config/custom_components/aarlo/cfg.py", line 389, in async_load_and_merge
    await self._async_load()
  File "/config/custom_components/aarlo/cfg.py", line 365, in _async_load
    self._main_config.update(config.get(COMPONENT_DOMAIN, {}))
                             ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Dan1jel** [comment]
Solved?  How? Explanation is appreciated.

**Comment by twrecked** [comment]
I'm guessing a broken/non-existing `aarlo.yaml` file. Can you post yours here?

I'll beef up the code to catch this error.

**Comment by platini76** [comment]
I really don't know how I solve.. :(
